using System;
using AiDotNet.Finance.Trading.Agents;
using AiDotNet.Models.Options;
using Xunit;
using static AiDotNet.Tests.UnitTests.Finance.FinancialAgentTestKit;

namespace AiDotNet.Tests.UnitTests.Finance;

/// <summary>
/// Evidence that <see cref="FinancialA2CAgent{T}"/> is on-policy and honours its rollout options.
/// </summary>
/// <remarks>
/// <para>
/// A2C's policy gradient is only valid for data generated by the policy being updated. The agent used to
/// sample a random minibatch from a replay buffer holding up to <c>ReplayBufferSize</c> (100,000 by default)
/// past transitions, with no importance weighting — so nearly every update was computed from actions taken
/// by a long-superseded policy. <c>NSteps</c> and <c>NumEnvironments</c> were settable but read by nothing.
/// </para>
/// </remarks>
public sealed class FinancialA2COnPolicyTests
{
    private const int StateSize = 4;
    private const int ActionSize = 3;

    private static FinancialA2CAgent<double> CreateAgent(int seed, int nSteps, int environments)
    {
        var options = (FinancialA2CAgentOptions<double>)Options(A2C, StateSize, ActionSize, seed);
        options.WarmupSteps = 0;
        options.BatchSize = 1;
        options.LearningRate = 0.01;
        options.NSteps = nSteps;
        options.NumEnvironments = environments;
        return (FinancialA2CAgent<double>)Create(A2C, options);
    }

    private static void Store(FinancialA2CAgent<double> agent, int index, bool done = false)
    {
        agent.StoreExperience(
            State(StateSize, salt: index),
            OneHot(ActionSize, index % ActionSize),
            0.1 * (index + 1),
            State(StateSize, salt: index + 1),
            done);
    }

    private static bool SameParameters(Vector<double> a, Vector<double> b)
    {
        if (a.Length != b.Length) return false;
        for (int i = 0; i < a.Length; i++)
        {
            if (a[i] != b[i]) return false;
        }

        return true;
    }

    [Fact]
    [Trait("category", "unit")]
    public void Update_waits_for_a_full_NSteps_rollout()
    {
        using var agent = CreateAgent(seed: 51, nSteps: 5, environments: 1);
        var initial = agent.GetParameters().Clone();

        for (int i = 0; i < 4; i++)
        {
            Store(agent, i);
            agent.Train();
        }

        // Pre-fix, BatchSize = 1 meant the very first stored transition triggered an update.
        Assert.True(SameParameters(initial, agent.GetParameters()),
            "A2C updated before a full NSteps rollout had been collected.");

        Store(agent, 4);
        agent.Train();

        Assert.False(SameParameters(initial, agent.GetParameters()),
            "A2C did not update once a full NSteps rollout was available.");
    }

    [Fact]
    [Trait("category", "unit")]
    public void Rollout_is_consumed_by_its_update_and_never_reused()
    {
        using var agent = CreateAgent(seed: 52, nSteps: 4, environments: 1);

        for (int i = 0; i < 4; i++)
        {
            Store(agent, i);
        }

        agent.Train();
        var afterFirstUpdate = agent.GetParameters().Clone();

        // No new experience has been collected, so an ON-POLICY agent has nothing left to learn from.
        // A replay-backed agent would happily resample the same stale transitions and update again.
        for (int i = 0; i < 5; i++)
        {
            agent.Train();
        }

        Assert.True(SameParameters(afterFirstUpdate, agent.GetParameters()),
            "A2C trained again from a rollout it had already consumed: the buffer is not cleared per update.");
    }

    [Fact]
    [Trait("category", "unit")]
    public void A_terminal_step_closes_a_short_rollout()
    {
        using var agent = CreateAgent(seed: 53, nSteps: 50, environments: 1);
        var initial = agent.GetParameters().Clone();

        Store(agent, 0);
        Store(agent, 1, done: true);
        agent.Train();

        Assert.False(SameParameters(initial, agent.GetParameters()),
            "a terminated episode did not trigger an update even though the rollout cannot grow further.");
    }

    [Fact]
    [Trait("category", "unit")]
    public void NumEnvironments_changes_how_returns_are_chained()
    {
        // Identical seeds and identical data; only the declared number of interleaved streams differs.
        // With one stream the n-step return chains straight down the list; with two, each stream is
        // chained separately, so the returns — and therefore the update — must differ.
        using var single = CreateAgent(seed: 54, nSteps: 8, environments: 1);
        using var interleaved = CreateAgent(seed: 54, nSteps: 8, environments: 2);

        for (int i = 0; i < 8; i++)
        {
            Store(single, i);
            Store(interleaved, i);
        }

        single.Train();
        interleaved.Train();

        Assert.False(SameParameters(single.GetParameters(), interleaved.GetParameters()),
            "NumEnvironments changed nothing: the rollout is chained identically regardless of the option.");
    }
}
