namespace AiDotNet.Enums;

public enum MatrixType
{
    Unknown = 0, 
    Square = 1, 
    Diagonal = 2, 
    Identity = 3, 
    Symmetric = 4, 
    SkewSymmetric = 5, 
    UpperTriangular = 6, 
    LowerTriangular = 7, 
    Rectangular = 8, 
    Zero = 9, 
    Scalar = 10, 
    UpperBidiagonal = 11, 
    LowerBidiagonal = 12, 
    Tridiagonal = 13, 
    Band = 14, 
    Hermitian = 15, 
    SkewHermitian = 16, 
    Orthogonal = 17, 
    Unitary = 18, 
    Singular = 19, 
    NonSingular = 20, 
    PositiveDefinite = 21, 
    PositiveSemiDefinite = 22, 
    OrthogonalProjection = 23, 
    Idempotent = 24, 
    Involutory = 25, 
    Stochastic = 26, 
    DoublyStochastic = 27, 
    Permutation = 28, 
    Adjacency = 29, 
    Incidence = 30, 
    Laplacian = 31, 
    Toeplitz = 32, 
    Hankel = 33, 
    Circulant = 34, 
    Block = 35,
    Sparse = 36, 
    Dense = 37, 
    Partitioned = 38, 
    Companion = 39, 
    Vandermonde = 40, 
    Hilbert = 41, 
    Cauchy = 42, 
}