namespace AiDotNet.Enums;

public enum ModelType
{
    SimpleRegression,
    MultipleRegression,
    MultivariateRegression,
    PolynomialRegression,
    WeightedRegression,
    RandomForest,
    DecisionTree,
    GradientBoosting,
    AdaBoostR2,
    ExtremelyRandomizedTrees,
    QuantileRegressionForests,
    ConditionalInferenceTree,
    M5ModelTree,
    NonLinearRegression,
    SupportVectorRegression,
    KernelRidgeRegression,
    GaussianProcessRegression,
    IsotonicRegression,
    QuantileRegression,
    RadialBasisFunctionRegression,
    LocallyWeightedRegression,
    SplineRegression,
    KNearestNeighbors,
    SymbolicRegression,
    BayesianRegression,
    ExpressionTree,
    Vector,
    GeneticAlgorithmRegression,
    OrthogonalRegression,
    RobustRegression,
    TimeSeriesRegression
}