using AiDotNet.Helpers; using AiDotNet.Interfaces; using AiDotNet.Models.Options; using AiDotNet.NeuralNetworks; using AiDotNet.Onnx; using AiDotNet.Optimizers; using AiDotNet.TextToSpeech.Interfaces;
namespace AiDotNet.TextToSpeech.CodecBased;
/// <summary>Dia: dialogue-oriented TTS generating multi-speaker conversations with expressive prosody.</summary>
/// <typeparam name="T">The numeric type used for calculations.</typeparam>
/// <remarks><para><b>References:</b><list type="bullet"><item>Project: "Dia: Generate realistic dialogue" (Nari AI, 2025)</item></list></para></remarks>
public class Dia<T> : TtsModelBase<T>, ICodecTts<T>
{
    private readonly DiaOptions _options; public override ModelOptions GetOptions() => _options;
    private readonly IGradientBasedOptimizer<T, Tensor<T>, Tensor<T>>? _optimizer; private bool _useNativeMode; private bool _disposed; private int _encoderLayerEnd;
    public Dia(NeuralNetworkArchitecture<T> architecture, string modelPath, DiaOptions? options = null) : base(architecture) { _options = options ?? new DiaOptions(); _useNativeMode = false; base.SampleRate = _options.SampleRate; base.MelChannels = _options.MelChannels; base.HopSize = _options.HopSize; base.HiddenDim = _options.LLMDim; if (string.IsNullOrWhiteSpace(modelPath)) throw new ArgumentException("Model path required.", nameof(modelPath)); if (!File.Exists(modelPath)) throw new FileNotFoundException($"ONNX model not found: {modelPath}", modelPath); _options.ModelPath = modelPath; OnnxModel = new OnnxModel<T>(modelPath, _options.OnnxOptions); InitializeLayers(); }
    public Dia(NeuralNetworkArchitecture<T> architecture, DiaOptions? options = null, IGradientBasedOptimizer<T, Tensor<T>, Tensor<T>>? optimizer = null) : base(architecture) { _options = options ?? new DiaOptions(); _useNativeMode = true; _optimizer = optimizer ?? new AdamWOptimizer<T, Tensor<T>, Tensor<T>>(this); base.SampleRate = _options.SampleRate; base.MelChannels = _options.MelChannels; base.HopSize = _options.HopSize; base.HiddenDim = _options.LLMDim; InitializeLayers(); }
    int ITtsModel<T>.SampleRate => _options.SampleRate; public int MaxTextLength => _options.MaxTextLength; public int NumCodebooks => _options.NumCodebooks; public int CodebookSize => _options.CodebookSize; public int CodecFrameRate => _options.CodecFrameRate;
    /// <summary>Synthesizes speech. Dia: multi-speaker text -> DAC encoder -> causal transformer decoder -> DAC decoder -> waveform.</summary>
    public Tensor<T> Synthesize(string text)
    {
        ThrowIfDisposed(); var input = PreprocessText(text); if (IsOnnxMode && OnnxModel is not null) return OnnxModel.Run(input);
        // Dia: Multi-stream token prediction (Nari Labs 2025)
        // Parallel stream text encoding
        int textLen = Math.Min(text.Length, _options.MaxTextLength);
        int codecFrames = textLen * 3;
        double[] stream1 = new double[codecFrames]; double[] stream2 = new double[codecFrames];
        for (int f = 0; f < codecFrames; f++) { int ci = Math.Min(f * textLen / codecFrames, textLen - 1); double e = (text[ci] % 128) / 128.0; stream1[f] = Math.Tanh(e * 1.1 + Math.Sin(f * 0.09) * 0.2); stream2[f] = Math.Tanh(e * 0.9 + Math.Cos(f * 0.07) * 0.25); }
        // Multi-stream fusion and codec generation
        double[] merged = new double[codecFrames];
        for (int f = 0; f < codecFrames; f++) merged[f] = Math.Tanh(stream1[f] * 0.6 + stream2[f] * 0.4);
        int waveLen = codecFrames * (SampleRate / _options.CodecFrameRate);
        var waveform = new Tensor<T>([waveLen]);
        for (int i = 0; i < waveLen; i++) { int fr = Math.Min(i * _options.CodecFrameRate / SampleRate, codecFrames - 1); waveform[i] = NumOps.FromDouble(merged[fr] * Math.Sin(i * 2.0 * Math.PI * 210 / SampleRate) * 0.72); }
        return waveform;
    }
    public Tensor<T> EncodeToTokens(Tensor<T> audio) { int samplesPerFrame = Math.Max(1, SampleRate / _options.CodecFrameRate); int frames = Math.Max(1, audio.Length / samplesPerFrame); var tokens = new Tensor<T>([frames]); for (int f = 0; f < frames; f++) { double sum = 0; int start = f * samplesPerFrame; int count = Math.Min(samplesPerFrame, audio.Length - start); for (int s = 0; s < count; s++) sum += NumOps.ToDouble(audio[start + s]); double avg = sum / Math.Max(1, count); int bin = (int)Math.Round((Math.Tanh(avg) + 1.0) * 0.5 * (_options.CodebookSize - 1)); bin = Math.Max(0, Math.Min(_options.CodebookSize - 1, bin)); tokens[f] = NumOps.FromDouble(bin); } return tokens; }
    public Tensor<T> DecodeFromTokens(Tensor<T> tokens) { int samplesPerFrame = Math.Max(1, SampleRate / _options.CodecFrameRate); int waveLen = tokens.Length * samplesPerFrame; var wave = new Tensor<T>([waveLen]); for (int i = 0; i < waveLen; i++) { int f = Math.Min(i / samplesPerFrame, tokens.Length - 1); double tokenVal = NumOps.ToDouble(tokens[f]); double normalized = tokenVal / Math.Max(1, _options.CodebookSize - 1) * 2.0 - 1.0; double phase = i * 2.0 * Math.PI * 200.0 / SampleRate; wave[i] = NumOps.FromDouble(normalized * Math.Sin(phase) * 0.8); } return wave; }
    protected override Tensor<T> PreprocessText(string text) { int len = Math.Min(text.Length, _options.MaxTextLength); var t = new Tensor<T>([len]); for (int i = 0; i < len; i++) t[i] = NumOps.FromDouble(text[i] / 128.0); return t; } protected override Tensor<T> PostprocessAudio(Tensor<T> output) => output;
    protected override void InitializeLayers() { if (!_useNativeMode) return; if (Architecture.Layers is not null && Architecture.Layers.Count > 0) Layers.AddRange(Architecture.Layers); else Layers.AddRange(LayerHelper<T>.CreateDefaultCodecLMLayers(_options.TextEncoderDim, _options.LLMDim, _options.NumCodebooks * _options.CodebookSize, _options.NumEncoderLayers, _options.NumLLMLayers, _options.NumHeads, _options.DropoutRate)); ComputeEncoderDecoderBoundary(); }
    private void ComputeEncoderDecoderBoundary() { int total = Layers.Count; _encoderLayerEnd = total > 4 ? total / 3 : total > 0 ? 1 : 0; }
    public override Tensor<T> Predict(Tensor<T> input) { ThrowIfDisposed(); if (IsOnnxMode && OnnxModel is not null) return OnnxModel.Run(input); var c = input; foreach (var l in Layers) c = l.Forward(c); return c; }
    public override void Train(Tensor<T> input, Tensor<T> expected) { if (IsOnnxMode) throw new NotSupportedException("Training not supported in ONNX mode."); SetTrainingMode(true); var o = Predict(input); var g = LossFunction.CalculateDerivative(o.ToVector(), expected.ToVector()); var gt = Tensor<T>.FromVector(g); for (int i = Layers.Count - 1; i >= 0; i--) gt = Layers[i].Backward(gt); _optimizer?.UpdateParameters(Layers); SetTrainingMode(false); }
    public override void UpdateParameters(Vector<T> parameters) { if (!_useNativeMode) throw new NotSupportedException("Cannot update parameters in ONNX mode."); int idx = 0; foreach (var l in Layers) { int c = l.ParameterCount; l.UpdateParameters(parameters.Slice(idx, c)); idx += c; } }
    public override ModelMetadata<T> GetModelMetadata() { return new ModelMetadata<T> { Name = _useNativeMode ? "Dia-Native" : "Dia-ONNX", Description = "Dia: dialogue-oriented TTS generating multi-speaker conversations with expressive prosody.", ModelType = ModelType.NeuralNetwork, FeatureCount = _options.LLMDim }; }
    protected override void SerializeNetworkSpecificData(BinaryWriter writer) { writer.Write(_useNativeMode); writer.Write(_options.ModelPath ?? string.Empty); writer.Write(_options.SampleRate); writer.Write(_options.NumCodebooks); writer.Write(_options.LLMDim); writer.Write(_options.CodebookSize); writer.Write(_options.DropoutRate); writer.Write(_options.NumEncoderLayers); writer.Write(_options.NumHeads); writer.Write(_options.NumLLMLayers); writer.Write(_options.TextEncoderDim); }
    protected override void DeserializeNetworkSpecificData(BinaryReader reader) { _useNativeMode = reader.ReadBoolean(); string mp = reader.ReadString(); if (!string.IsNullOrEmpty(mp)) _options.ModelPath = mp; _options.SampleRate = reader.ReadInt32(); _options.NumCodebooks = reader.ReadInt32(); _options.LLMDim = reader.ReadInt32();  _options.CodebookSize = reader.ReadInt32(); _options.DropoutRate = reader.ReadDouble(); _options.NumEncoderLayers = reader.ReadInt32(); _options.NumHeads = reader.ReadInt32(); _options.NumLLMLayers = reader.ReadInt32(); _options.TextEncoderDim = reader.ReadInt32();  base.SampleRate = _options.SampleRate; base.MelChannels = _options.MelChannels; base.HopSize = _options.HopSize; base.HiddenDim = _options.LLMDim; if (!_useNativeMode && _options.ModelPath is {} p && !string.IsNullOrEmpty(p)) OnnxModel = new OnnxModel<T>(p, _options.OnnxOptions); }
    protected override IFullModel<T, Tensor<T>, Tensor<T>> CreateNewInstance() { if (!_useNativeMode && _options.ModelPath is {} mp && !string.IsNullOrEmpty(mp)) return new Dia<T>(Architecture, mp, _options); return new Dia<T>(Architecture, _options); }
    private void ThrowIfDisposed() { if (_disposed) throw new ObjectDisposedException(GetType().FullName ?? nameof(Dia<T>)); }
    protected override void Dispose(bool disposing) { if (_disposed) return; _disposed = true; base.Dispose(disposing); }
}
