// <auto-generated>
// This file is generated from CLBlast database headers.
// </auto-generated>
namespace AiDotNet.Tensors.Engines.DirectGpu.OpenCL;

internal static class ClBlastXgemmDirectDatabaseData
{
    internal static readonly ClBlastVendorEntry[] Vendors = new[]
    {
        new ClBlastVendorEntry("GPU", "AMD", new[]
        {
            new ClBlastArchitectureEntry("Ellesmere", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 480", new short[] { 2, 8, 8, 32, 32, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon RX 580 2048SP", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon RX590 GME", new short[] { 2, 8, 8, 32, 32, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 32, 32, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("Fiji", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon R9 Fury X", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon R9 M370X Compute Engine", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("Hawaii", new[]
            {
                new ClBlastDeviceEntry("AMD FirePro W8100", new short[] { 2, 8, 8, 32, 32, 1, 1, 4, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 32, 32, 1, 1, 4, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("Tonga", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon R9 380", new short[] { 16, 16, 16, 32, 8, 0, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 16, 16, 16, 32, 8, 0, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("Turks", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon HD 6770M", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("Vancouver", new[]
            {
                new ClBlastDeviceEntry("ATI Radeon HD 6750M", new short[] { 8, 8, 16, 8, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 8, 8, 16, 8, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon Pro 450 Compute Engine", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon Pro 580 Compute Engine", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1010:xnack-", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 5700", new short[] { 2, 8, 8, 16, 16, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon RX 5700 XT", new short[] { 2, 16, 16, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            // RX 5500 XT (gfx1012) - RDNA1 with 11 CUs, optimized for smaller workgroups
            new ClBlastArchitectureEntry("gfx1012:xnack-", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 5500 XT", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1030", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 6800 XT", new short[] { 2, 16, 16, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon RX 6900 XT", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 2, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1031", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 6700 XT", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1032", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 6600 XT", new short[] { 2, 8, 8, 16, 16, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1034", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 6500 XT", new short[] { 8, 16, 16, 32, 16, 1, 1, 4, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 8, 16, 16, 32, 16, 1, 1, 4, 1, 64, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1035", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon Graphics", new short[] { 8, 8, 8, 8, 8, 1, 1, 8, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 8, 8, 8, 8, 8, 1, 1, 8, 4, 64, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1036", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon Graphics", new short[] { 2, 8, 16, 8, 8, 1, 1, 4, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 16, 8, 8, 1, 1, 4, 4, 64, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1100", new[]
            {
                new ClBlastDeviceEntry("Radeon RX 7900 XTX", new short[] { 2, 8, 8, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1101", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 7800 XT", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1102", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 7600", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1103", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon 780M Graphics", new short[] { 2, 16, 16, 16, 16, 1, 1, 2, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 16, 16, 1, 1, 2, 4, 64, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx1201", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon RX 9070 XT", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 8, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 8, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx902", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon(TM) Graphics", new short[] { 8, 16, 8, 16, 8, 1, 0, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon(TM) RX Vega 10 Graphics", new short[] { 2, 16, 16, 32, 8, 1, 0, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx906:sramecc+:xnack-", new[]
            {
                new ClBlastDeviceEntry("AMD Instinct MI50/MI60", new short[] { 16, 16, 16, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("AMD Radeon VII", new short[] { 16, 16, 16, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 16, 16, 16, 16, 16, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("gfx90c", new[]
            {
                new ClBlastDeviceEntry("AMD Radeon(TM) Graphics", new short[] { 8, 16, 8, 16, 8, 1, 0, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 16, 8, 16, 16, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "ARM", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("Mali-T628", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Mali-T760", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "Apple", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("Apple M1", new short[] { 2, 16, 16, 16, 16, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Apple M2 Max", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "Imagination Technologies", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("PowerVR B-Series BXE-4-32", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("CPU", "Intel", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz", new short[] { 2, 8, 8, 8, 8, 0, 0, 1, 8, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz", new short[] { 8, 16, 16, 16, 16, 0, 0, 1, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz", new short[] { 8, 8, 8, 8, 8, 0, 0, 8, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz", new short[] { 2, 32, 32, 32, 32, 0, 0, 1, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", new short[] { 16, 16, 8, 8, 8, 0, 0, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz", new short[] { 2, 8, 8, 8, 8, 0, 0, 2, 2, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz", new short[] { 2, 8, 8, 16, 8, 0, 0, 4, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz", new short[] { 8, 32, 32, 32, 16, 0, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz", new short[] { 16, 8, 16, 16, 16, 0, 0, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz", new short[] { 16, 8, 16, 16, 16, 0, 0, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("cpu-penryn-Intel(R) Core(TM)2 Duo CPU     T6670  @", new short[] { 16, 16, 8, 8, 8, 0, 0, 4, 2, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "Intel", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("Intel(R) Arc(TM) A750 Graphics", new short[] { 8, 32, 32, 16, 8, 1, 0, 1, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Arc(TM) A770 Graphics", new short[] { 2, 32, 32, 16, 16, 0, 0, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) HD Graphics 6000 BroadWell U-Processor GT", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) HD Graphics 620", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) HD Graphics IvyBridge M GT2", new short[] { 8, 16, 32, 16, 8, 1, 0, 1, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) HD Graphics Skylake ULT GT2", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 8, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Iris(R) Plus Graphics 640", new short[] { 16, 16, 16, 8, 8, 1, 0, 2, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) Iris(R) Xe Graphics", new short[] { 8, 16, 16, 8, 8, 0, 0, 4, 2, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) RaptorLake-S Mobile Graphics Controller", new short[] { 8, 16, 16, 8, 8, 0, 0, 4, 2, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) UHD Graphics", new short[] { 8, 32, 16, 8, 8, 1, 0, 2, 8, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) UHD Graphics 620", new short[] { 8, 32, 16, 8, 8, 1, 0, 2, 8, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Intel(R) UHD Graphics 770", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Iris Pro", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 4, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("accelerator", "Intel", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("Intel(R) FPGA Emulation Device", new short[] { 2, 8, 32, 8, 8, 0, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 32, 8, 8, 0, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "NVIDIA", new[]
        {
            new ClBlastArchitectureEntry("SM12.0", new[]
            {
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 5070 Ti", new short[] { 2, 16, 8, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 5080", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM2.0", new[]
            {
                new ClBlastDeviceEntry("GeForce GTX 580", new short[] { 2, 16, 8, 32, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 8, 32, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM3.0", new[]
            {
                new ClBlastDeviceEntry("GeForce GT 650M", new short[] { 16, 16, 16, 8, 16, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX 760 Ti OEM", new short[] { 16, 32, 8, 16, 16, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 16, 16, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM3.5", new[]
            {
                new ClBlastDeviceEntry("GeForce 920A", new short[] { 16, 32, 8, 32, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX TITAN Black", new short[] { 2, 8, 8, 16, 16, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce GT 730", new short[] { 16, 8, 16, 32, 8, 1, 0, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 16, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM5.0", new[]
            {
                new ClBlastDeviceEntry("GeForce 920MX", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX 750 Ti", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Quadro M2000M", new short[] { 2, 16, 8, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM5.2", new[]
            {
                new ClBlastDeviceEntry("GeForce GTX 970", new short[] { 2, 8, 8, 32, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 32, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM6.0", new[]
            {
                new ClBlastDeviceEntry("Tesla P100-PCIE-16GB", new short[] { 16, 8, 8, 16, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 16, 8, 8, 16, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM6.1", new[]
            {
                new ClBlastDeviceEntry("GeForce GTX 1050 Ti", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX 1070 Ti", new short[] { 2, 16, 8, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX 1080", new short[] { 16, 16, 8, 16, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("GeForce GTX 1080 Ti", new short[] { 16, 8, 8, 16, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce GTX 1060 6GB", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce MX150", new short[] { 8, 32, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("TITAN X (Pascal)", new short[] { 8, 32, 8, 8, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Tesla P4", new short[] { 8, 16, 8, 16, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM7.0", new[]
            {
                new ClBlastDeviceEntry("Quadro GV100", new short[] { 2, 8, 8, 16, 16, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Tesla V100-PCIE-16GB", new short[] { 2, 16, 16, 16, 16, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 16, 16, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM7.5", new[]
            {
                new ClBlastDeviceEntry("GeForce GTX 1650", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce GTX 1650 SUPER", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce GTX 1650 Ti", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce MX450", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2060", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2070 SUPER", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2070 Super", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2070 with Max-Q Design", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2080 Ti", new short[] { 8, 16, 8, 16, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2080 with Max-Q Design", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Quadro T2000", new short[] { 8, 16, 8, 16, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("TITAN RTX", new short[] { 16, 8, 16, 32, 8, 1, 0, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("Tesla T4", new short[] { 8, 16, 8, 16, 8, 1, 0, 2, 2, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM8.0", new[]
            {
                new ClBlastDeviceEntry("A100-PCIE-40GB", new short[] { 8, 8, 16, 32, 16, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 8, 8, 16, 32, 16, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM8.6", new[]
            {
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 2050", new short[] { 2, 16, 8, 8, 16, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3050 Laptop GPU", new short[] { 8, 16, 8, 8, 32, 1, 1, 2, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3050 Ti Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3060", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3060 Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3070", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3070 Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3070 Ti Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3080", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3080 Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3080 Ti", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 3090", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA RTX A6000", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("SM8.9", new[]
            {
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4050 Laptop GPU", new short[] { 8, 16, 8, 16, 8, 1, 0, 1, 1, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4060", new short[] { 8, 32, 32, 8, 8, 1, 0, 2, 4, 64, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4060 Laptop GPU", new short[] { 16, 32, 8, 32, 16, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4060 Ti", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4070 Laptop GPU", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4070 Ti", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4080", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("NVIDIA GeForce RTX 4090", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("GPU", "QUALCOMM", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM)", new short[] { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("OpenCL C 2.0 Adreno(TM) 640", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM)", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 1, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("OpenCL C 2.0 Adreno(TM) 650", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM)", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("OpenCL C 3.0 Adreno(TM) 730", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM)", new short[] { 8, 16, 16, 8, 8, 0, 0, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 8, 16, 16, 8, 8, 0, 0, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("OpenCL C 3.0 Adreno(TM) 735", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM) 735", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 2, 4, 32, 0, 0, 0, 0, 0, 0 }),
            }),
            new ClBlastArchitectureEntry("OpenCL C 3.0 Adreno(TM) 740", new[]
            {
                new ClBlastDeviceEntry("QUALCOMM Adreno(TM)", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
                new ClBlastDeviceEntry("default", new short[] { 2, 16, 16, 8, 8, 1, 1, 2, 1, 32, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
        new ClBlastVendorEntry("default", "default", new[]
        {
            new ClBlastArchitectureEntry("default", new[]
            {
                new ClBlastDeviceEntry("default", new short[] { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16, 0, 0, 0, 0, 0, 0 }),
            }),
        }),
    };
}

