using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AiDotNet.Generators;

/// <summary>
/// Roslyn incremental source generator that turns methods marked with
/// <c>[AiDotNet.Agentic.Tools.AgentTool]</c> into reflection-free agent tools at compile time.
/// </summary>
/// <remarks>
/// <para>
/// For each type that declares one or more <c>[AgentTool]</c> methods, this generator emits a
/// <c>CreateAgentTools(this T instance)</c> extension that returns a list of
/// <c>FunctionAgentTool</c>s. Each tool carries a JSON schema computed at generation time (no runtime
/// reflection) and a typed argument binder that deserializes the model's JSON arguments and calls the
/// method directly. This is the AOT-friendly counterpart to the reflection-based
/// <c>AgentToolFactory.ScanInstance</c>.
/// </para>
/// <para>
/// Supported parameter schema kinds: primitives, <c>string</c>/<c>char</c>, enums (as string enums),
/// <c>DateTime</c>/<c>DateTimeOffset</c>/<c>Guid</c>/<c>TimeSpan</c>, arrays and
/// <c>IEnumerable&lt;T&gt;</c>, and string-keyed dictionaries; other complex types fall back to a bare
/// <c>{"type":"object"}</c> schema (their arguments still bind via JSON deserialization). Omitted
/// optional arguments bind to <c>default(T)</c>.
/// </para>
/// </remarks>
[Generator]
public class AgentToolSchemaGenerator : IIncrementalGenerator
{
    private const string ToolAttribute = "AgentToolAttribute";
    private const string ParamAttribute = "ToolParameterAttribute";
    private const string ToolsNamespace = "AiDotNet.Agentic.Tools";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as IMethodSymbol)
            .Where(static m => m is not null && HasToolAttribute(m))
            .Collect();

        context.RegisterSourceOutput(methods, static (spc, ms) => Execute(spc, ms));
    }

    private static bool HasToolAttribute(IMethodSymbol method) =>
        method.GetAttributes().Any(a =>
            a.AttributeClass?.Name == ToolAttribute &&
            a.AttributeClass.ContainingNamespace?.ToDisplayString() == ToolsNamespace);

    private static void Execute(SourceProductionContext context, ImmutableArray<IMethodSymbol?> methods)
    {
        if (methods.IsDefaultOrEmpty) return;

        // Group accessible, non-generic [AgentTool] methods by their containing type.
        var byType = new Dictionary<INamedTypeSymbol, List<IMethodSymbol>>(SymbolEqualityComparer.Default);
        foreach (var method in methods)
        {
            if (method is null) continue;
            if (method.IsGenericMethod) continue;
            if (method.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)) continue;

            var owner = method.ContainingType;
            if (owner is null || owner.IsGenericType) continue;
            if (owner.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)) continue;
            if (owner.TypeKind is not (TypeKind.Class or TypeKind.Struct)) continue;

            if (!byType.TryGetValue(owner, out var list))
            {
                list = new List<IMethodSymbol>();
                byType[owner] = list;
            }

            list.Add(method);
        }

        foreach (var pair in byType)
        {
            var source = EmitFactory(pair.Key, pair.Value);
            var hint = pair.Key.ToDisplayString().Replace("<", "_").Replace(">", "_").Replace(",", "_").Replace(" ", "");
            context.AddSource($"{hint}.AgentTools.g.cs", source);
        }
    }

    private static string EmitFactory(INamedTypeSymbol owner, List<IMethodSymbol> toolMethods)
    {
        var fqType = owner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var ns = owner.ContainingNamespace.IsGlobalNamespace ? null : owner.ContainingNamespace.ToDisplayString();
        var factoryName = owner.Name + "AgentToolFactory";
        // The generated factory must not be more accessible than the type it extends (CS0051).
        var access = owner.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable disable");
        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    /// <summary>Source-generated agent-tool factory for {fqType}.</summary>");
        sb.AppendLine($"    {access} static class {factoryName}");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Creates the agent tools declared by [AgentTool] methods on this instance.</summary>");
        sb.AppendLine($"        {access} static global::System.Collections.Generic.IReadOnlyList<global::AiDotNet.Agentic.Tools.IAgentTool> CreateAgentTools(this {fqType} instance)");
        sb.AppendLine("        {");
        sb.AppendLine("            return new global::AiDotNet.Agentic.Tools.IAgentTool[]");
        sb.AppendLine("            {");

        foreach (var method in toolMethods)
        {
            EmitTool(sb, fqType, method);
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void EmitTool(StringBuilder sb, string fqType, IMethodSymbol method)
    {
        var attr = method.GetAttributes().First(a =>
            a.AttributeClass?.Name == ToolAttribute &&
            a.AttributeClass.ContainingNamespace?.ToDisplayString() == ToolsNamespace);

        var description = attr.ConstructorArguments.Length > 0 ? attr.ConstructorArguments[0].Value as string ?? "" : "";
        var explicitName = attr.NamedArguments.FirstOrDefault(n => n.Key == "Name").Value.Value as string;
        var toolName = string.IsNullOrWhiteSpace(explicitName) ? method.Name : explicitName;

        var schemaJson = BuildSchemaJson(method);

        sb.AppendLine("                new global::AiDotNet.Agentic.Tools.FunctionAgentTool(");
        sb.AppendLine($"                    {Verbatim(toolName)},");
        sb.AppendLine($"                    {Verbatim(description)},");
        sb.AppendLine($"                    global::Newtonsoft.Json.Linq.JObject.Parse({Verbatim(schemaJson)}),");

        // Determine the (a)synchrony of the method and build the invoker lambda accordingly.
        var (isAsync, resultType) = ClassifyReturn(method.ReturnType);
        var lambdaPrefix = isAsync ? "async " : "";
        sb.AppendLine($"                    {lambdaPrefix}(global::Newtonsoft.Json.Linq.JObject args, global::System.Threading.CancellationToken ct) =>");
        sb.AppendLine("                    {");

        var callArgs = new List<string>();
        foreach (var p in method.Parameters)
        {
            if (IsCancellationToken(p.Type))
            {
                callArgs.Add("ct");
                continue;
            }

            var pType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var local = "__p_" + p.Name;
            var token = "__t_" + p.Name;

            // Three-way binding, parity with DelegateAgentTool:
            //  - if the parameter has an explicit declared default, use it
            //    (preserves method intent like `int limit = 10`);
            //  - else if the parameter is a non-nullable value type, treat
            //    a missing argument as an error rather than silently binding
            //    to `default(T)` (0 / false), which would change semantics;
            //  - else allow null (reference / Nullable<T>).
            bool isValueType = p.Type.IsValueType
                && p.Type.OriginalDefinition?.SpecialType != SpecialType.System_Nullable_T;
            string missingHandler;
            if (p.HasExplicitDefaultValue)
            {
                missingHandler = GetParameterDefaultLiteral(p, pType);
            }
            else if (isValueType)
            {
                missingHandler = $"throw new global::System.ArgumentException(\"Missing required parameter '{p.Name}'.\", {Verbatim(p.Name)})";
            }
            else
            {
                missingHandler = $"default({pType})";
            }
            sb.AppendLine($"                        var {local} = args.TryGetValue({Verbatim(p.Name)}, out var {token}) && {token}.Type != global::Newtonsoft.Json.Linq.JTokenType.Null");
            sb.AppendLine($"                            ? {token}.ToObject<{pType}>()");
            sb.AppendLine($"                            : {missingHandler};");
            callArgs.Add(local);
        }

        var target = method.IsStatic ? fqType : "instance";
        var call = $"{target}.{method.Name}({string.Join(", ", callArgs)})";

        if (isAsync)
        {
            if (resultType is null)
            {
                sb.AppendLine($"                        await {call};");
                sb.AppendLine("                        return global::System.String.Empty;");
            }
            else
            {
                sb.AppendLine($"                        var __r = await {call};");
                sb.AppendLine($"                        return {ResultToString(resultType, "__r")};");
            }
        }
        else
        {
            if (method.ReturnsVoid)
            {
                sb.AppendLine($"                        {call};");
                sb.AppendLine("                        return global::System.Threading.Tasks.Task.FromResult(global::System.String.Empty);");
            }
            else
            {
                sb.AppendLine($"                        var __r = {call};");
                sb.AppendLine($"                        return global::System.Threading.Tasks.Task.FromResult({ResultToString(method.ReturnType, "__r")});");
            }
        }

        sb.AppendLine("                    }),");
    }

    private static string ResultToString(ITypeSymbol type, string varName) =>
        type.SpecialType == SpecialType.System_String
            ? $"({varName} ?? global::System.String.Empty)"
            : $"global::Newtonsoft.Json.JsonConvert.SerializeObject({varName})";

    private static (bool IsAsync, ITypeSymbol? ResultType) ClassifyReturn(ITypeSymbol returnType)
    {
        if (returnType is INamedTypeSymbol named &&
            named.ContainingNamespace?.ToDisplayString() == "System.Threading.Tasks" &&
            (named.Name == "Task" || named.Name == "ValueTask"))
        {
            return named.TypeArguments.Length == 1 ? (true, named.TypeArguments[0]) : (true, null);
        }

        return (false, null);
    }

    private static bool IsCancellationToken(ITypeSymbol type) =>
        type.Name == "CancellationToken" && type.ContainingNamespace?.ToDisplayString() == "System.Threading";

    // ── Schema (computed at generation time, emitted as a JSON string) ──

    private static string BuildSchemaJson(IMethodSymbol method)
    {
        var props = new List<string>();
        var required = new List<string>();

        foreach (var p in method.Parameters)
        {
            if (IsCancellationToken(p.Type)) continue;

            var schema = TypeSchemaJson(Unwrap(p.Type));

            var paramAttr = p.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.Name == ParamAttribute &&
                a.AttributeClass.ContainingNamespace?.ToDisplayString() == ToolsNamespace);
            if (paramAttr is not null)
            {
                var desc = paramAttr.ConstructorArguments.Length > 0 ? paramAttr.ConstructorArguments[0].Value as string : null;
                if (!string.IsNullOrWhiteSpace(desc))
                {
                    schema = schema.Substring(0, schema.Length - 1) + $",\"description\":{JsonString(desc)}}}";
                }
            }

            props.Add($"{JsonString(p.Name)}:{schema}");

            if (IsRequired(p, paramAttr))
            {
                required.Add(JsonString(p.Name));
            }
        }

        var sb = new StringBuilder("{\"type\":\"object\",\"properties\":{");
        sb.Append(string.Join(",", props));
        sb.Append("}");
        if (required.Count > 0)
        {
            sb.Append(",\"required\":[").Append(string.Join(",", required)).Append("]");
        }

        sb.Append("}");
        return sb.ToString();
    }

    // Emits the C# literal for a parameter's declared default value so the generated binder reproduces the
    // method's optional-parameter semantics. Caller guarantees p.HasExplicitDefaultValue.
    private static string GetParameterDefaultLiteral(IParameterSymbol p, string pType)
    {
        var value = p.ExplicitDefaultValue;
        switch (value)
        {
            case null:
                // Covers `string s = null`, nullable value types defaulting to null, etc.
                return $"default({pType})";
            case bool b:
                return b ? "true" : "false";
            case string s:
                return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(s, quote: true);
            case char c:
                return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(c, quote: true);
            default:
                // Numeric default, or an enum (whose ExplicitDefaultValue is the underlying constant): emit the
                // invariant numeric literal cast to the parameter type so suffixes/enum typing are correct.
                var literal = System.Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture);
                return $"({pType})({literal})";
        }
    }

    private static bool IsRequired(IParameterSymbol p, AttributeData? paramAttr)
    {
        if (paramAttr is not null)
        {
            var explicitReq = paramAttr.NamedArguments.FirstOrDefault(n => n.Key == "Required").Value;
            if (explicitReq.Value is bool b)
            {
                return b;
            }
        }

        if (p.IsOptional || p.HasExplicitDefaultValue) return false;

        // A nullable-annotated reference type (string?, MyDto?) is optional, just like a Nullable<T> value type.
        if (p.NullableAnnotation == NullableAnnotation.Annotated) return false;

        return p.Type is not INamedTypeSymbol n || n.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T;
    }

    private static ITypeSymbol Unwrap(ITypeSymbol type) =>
        type is INamedTypeSymbol n && n.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            ? n.TypeArguments[0]
            : type;

    private static string TypeSchemaJson(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Enum)
        {
            var names = type.GetMembers().OfType<IFieldSymbol>()
                .Where(f => f.IsStatic && f.HasConstantValue)
                .Select(f => JsonString(f.Name));
            return $"{{\"type\":\"string\",\"enum\":[{string.Join(",", names)}]}}";
        }

        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
                return "{\"type\":\"boolean\"}";
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt64:
                return "{\"type\":\"integer\"}";
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_Decimal:
                return "{\"type\":\"number\"}";
            case SpecialType.System_Char:
            case SpecialType.System_String:
                return "{\"type\":\"string\"}";
            case SpecialType.System_DateTime:
                return "{\"type\":\"string\",\"format\":\"date-time\"}";
        }

        switch (type.Name)
        {
            case "Guid":
                return "{\"type\":\"string\",\"format\":\"uuid\"}";
            case "DateTimeOffset":
                return "{\"type\":\"string\",\"format\":\"date-time\"}";
            case "TimeSpan":
                return "{\"type\":\"string\",\"format\":\"duration\"}";
        }

        if (type is IArrayTypeSymbol array)
        {
            return $"{{\"type\":\"array\",\"items\":{TypeSchemaJson(Unwrap(array.ElementType))}}}";
        }

        if (TryGetDictionaryValueType(type, out var valueType))
        {
            return $"{{\"type\":\"object\",\"additionalProperties\":{TypeSchemaJson(Unwrap(valueType))}}}";
        }

        if (TryGetEnumerableElementType(type, out var elementType))
        {
            return $"{{\"type\":\"array\",\"items\":{TypeSchemaJson(Unwrap(elementType))}}}";
        }

        return "{\"type\":\"object\"}";
    }

    private static bool TryGetDictionaryValueType(ITypeSymbol type, out ITypeSymbol valueType)
    {
        foreach (var i in EnumerateSelfAndInterfaces(type))
        {
            if (i is INamedTypeSymbol n && n.IsGenericType &&
                n.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>" &&
                n.TypeArguments.Length == 2 && n.TypeArguments[0].SpecialType == SpecialType.System_String)
            {
                valueType = n.TypeArguments[1];
                return true;
            }
        }

        valueType = type;
        return false;
    }

    private static bool TryGetEnumerableElementType(ITypeSymbol type, out ITypeSymbol elementType)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            elementType = type;
            return false;
        }

        foreach (var i in EnumerateSelfAndInterfaces(type))
        {
            if (i is INamedTypeSymbol n && n.IsGenericType &&
                n.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>")
            {
                elementType = n.TypeArguments[0];
                return true;
            }
        }

        elementType = type;
        return false;
    }

    private static IEnumerable<ITypeSymbol> EnumerateSelfAndInterfaces(ITypeSymbol type)
    {
        yield return type;
        foreach (var i in type.AllInterfaces)
        {
            yield return i;
        }
    }

    // ── String literal helpers ──

    /// <summary>Produces a C# verbatim string literal (@"...") with embedded quotes doubled.</summary>
    private static string Verbatim(string? value) => "@\"" + (value ?? "").Replace("\"", "\"\"") + "\"";

    /// <summary>Produces a JSON string literal (with surrounding quotes) for schema construction.</summary>
    private static string JsonString(string? value)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in value ?? "")
        {
            switch (c)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }

        sb.Append("\"");
        return sb.ToString();
    }
}
