namespace AiDotNet.Generators;

/// <summary>
/// Checked-in baselines for the defect-class diagnostics: every existing violation, listed so that a NEW
/// violation is a compile error while the known ones are worked down.
/// </summary>
/// <remarks>
/// <para>
/// A baseline may only shrink. An entry that no longer violates (the model gained tests, or was deleted)
/// is itself an error (ADNGEN002), so a fix cannot land without removing its line. That keeps the list an
/// exact inventory of the remaining debt rather than a growing allowlist.
/// </para>
/// <para>
/// Parking a known defect class in prose is how the same defects recurred; this is the ratchet in code.
/// </para>
/// </remarks>
internal static class DefectBaselines
{
    /// <summary>
    /// Models with no generated or hand-written test class when AIDN040 became an error (2026-09-28): 328
    /// of 1807. Keyed by fully qualified name because simple names collide.
    /// </summary>
    internal static readonly System.Collections.Generic.HashSet<string> UntestedModels =
        new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)
        {
            "global::AiDotNet.AnomalyDetection.NeuralNetwork.AnoGANDetector<T>",
            "global::AiDotNet.AnomalyDetection.NeuralNetwork.GANomalyDetector<T>",
            "global::AiDotNet.Audio.Classification.AudioLDMClassifier<T>",
            "global::AiDotNet.Audio.Features.ConstantQTransform<T>",
            "global::AiDotNet.Audio.LanguageIdentification.ECAPATDNNLanguageIdentifier<T>",
            "global::AiDotNet.Audio.LanguageIdentification.Wav2Vec2LanguageIdentifier<T>",
            "global::AiDotNet.Audio.TextToSpeech.CosyVoice2<T>",
            "global::AiDotNet.Audio.TextToSpeech.MatchaTTS<T>",
            "global::AiDotNet.Audio.TextToSpeech.StyleTTS2<T>",
            "global::AiDotNet.AutoML.AutoMLEnsembleModel<T>",
            "global::AiDotNet.AutoML.DiffusionAutoML<T>",
            "global::AiDotNet.AutoML.DiffusionAutoMLModel<T>",
            "global::AiDotNet.ComputerVision.Detection.Necks.BiFPN<T>",
            "global::AiDotNet.ComputerVision.Detection.Necks.FPN<T>",
            "global::AiDotNet.ComputerVision.Detection.Necks.PANet<T>",
            "global::AiDotNet.ComputerVision.Segmentation.Referring.GLaMM<T>",
            "global::AiDotNet.ComputerVision.Segmentation.Semantic.DiffCut<T>",
            "global::AiDotNet.ComputerVision.Segmentation.Semantic.DiffSeg<T>",
            "global::AiDotNet.ContinualLearning.Memory.ExperienceReplayBuffer<T, TInput, TOutput>",
            "global::AiDotNet.Diffusion.Conditioning.ChatGLM3TextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.CLIPTextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.DistilledT5TextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.GemmaTextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.Qwen2TextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.SigLIP2TextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.SigLIPTextConditioner<T>",
            "global::AiDotNet.Diffusion.Conditioning.T5TextConditioner<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.AsymmDiTPredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.DiTNoisePredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.EMMDiTPredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.FlagDiTPredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.FluxDoubleStreamPredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.MMDiTNoisePredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.MMDiTXNoisePredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.SiTPredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.UNetNoisePredictor<T>",
            "global::AiDotNet.Diffusion.NoisePredictors.UViTNoisePredictor<T>",
            "global::AiDotNet.Diffusion.VAE.AudioVAE<T>",
            "global::AiDotNet.Diffusion.VAE.AutoencoderKL<T>",
            "global::AiDotNet.Diffusion.VAE.Causal3DVAE<T>",
            "global::AiDotNet.Diffusion.VAE.DeepCompressionVAE<T>",
            "global::AiDotNet.Diffusion.VAE.EQVAEModel<T>",
            "global::AiDotNet.Diffusion.VAE.ImprovedVideoVAE<T>",
            "global::AiDotNet.Diffusion.VAE.LiteVAEModel<T>",
            "global::AiDotNet.Diffusion.VAE.SDXLVAEModel<T>",
            "global::AiDotNet.Diffusion.VAE.StandardVAE<T>",
            "global::AiDotNet.Diffusion.VAE.TemporalInterpolationVAE<T>",
            "global::AiDotNet.Diffusion.VAE.TemporalVAE<T>",
            "global::AiDotNet.DistributedTraining.DDPModel<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.FSDPModel<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.HybridShardedModel<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.PipelineParallelModel<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.TensorParallelModel<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.TensorParallelPagedModel<T>",
            "global::AiDotNet.DistributedTraining.ZeRO1Model<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.ZeRO2Model<T, TInput, TOutput>",
            "global::AiDotNet.DistributedTraining.ZeRO3Model<T, TInput, TOutput>",
            "global::AiDotNet.Finance.AutoML.FinancialAutoML<T>",
            "global::AiDotNet.Finance.Forecasting.Foundation.CCDM<T>",
            "global::AiDotNet.Finance.Forecasting.Foundation.CSDI<T>",
            "global::AiDotNet.Finance.Forecasting.Foundation.TimeDiff<T>",
            "global::AiDotNet.Finance.Forecasting.Foundation.TimeGrad<T>",
            "global::AiDotNet.Finance.Forecasting.Foundation.TSDiff<T>",
            "global::AiDotNet.Finance.Forecasting.Transformers.TSMixer<T>",
            "global::AiDotNet.Finance.Probabilistic.CSDI<T>",
            "global::AiDotNet.Finance.Probabilistic.DiffusionTS<T>",
            "global::AiDotNet.Finance.Probabilistic.ScoreGrad<T>",
            "global::AiDotNet.Finance.Probabilistic.TimeGrad<T>",
            "global::AiDotNet.Finance.Probabilistic.TSDiff<T>",
            "global::AiDotNet.Finance.Trading.Agents.FinancialA2CAgent<T>",
            "global::AiDotNet.Finance.Trading.Agents.FinancialPPOAgent<T>",
            "global::AiDotNet.Finance.Trading.Agents.FinancialSACAgent<T>",
            "global::AiDotNet.Finance.Trading.Agents.FinRLAgent<T>",
            "global::AiDotNet.Finance.Volatility.EGarchModel<T>",
            "global::AiDotNet.Finance.Volatility.Garch11Model<T>",
            "global::AiDotNet.Finance.Volatility.GjrGarchModel<T>",
            "global::AiDotNet.Finance.Volatility.NeuralGARCH<T>",
            "global::AiDotNet.Finance.Volatility.RealizedVolatilityTransformer<T>",
            "global::AiDotNet.GaussianProcesses.MultiOutputGaussianProcess<T>",
            "global::AiDotNet.GaussianProcesses.MultiTaskGaussianProcess<T>",
            "global::AiDotNet.KnowledgeDistillation.FeatureDistillationStrategy<T>",
            "global::AiDotNet.MetaLearning.Algorithms.ACLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ActiveTransFSLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.AdaptedMetaModel<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ANILAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ANPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ATAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.AutoLoRAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.BayProNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.BayTransProtoAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.BMAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.BOILAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.CAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.CAVIAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.CNAPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.CNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ConstellationNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ContextMetaRLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ConvCNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ConvNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DeepEMDAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DiscoRLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DKTAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DPGNAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DREAMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.DynamicTaskSamplingAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.EPNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.EquivCNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ETPNAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.FEATAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.FewTUREAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.FreqPriorAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.FreqPromptAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.FRNAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.GNNMetaAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.HyperCLIPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.HyperMAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.HyperNeRFMetaAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.HyperNetMetaRLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.HyperShotAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ICMFusionAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.InContextRLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.iTAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.JMPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.LaplacianShotAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.LBANPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.LEOAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.LFTAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.LoRARecycleAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MAMLPlusPlusAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MANNAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MatchingNetworksAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MbPAAdaptedModel<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MbPAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MCLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaBaselineAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaCollaborativeAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaDDPMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaDiffAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaDMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaFDMixupAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaLoRAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaLoRABankAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaOptNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaPACOHAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaSGDAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MetaTaskAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MOCAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.MPTSAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.NeuralProcessModel<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.NPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.NPBMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.NTMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.OMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.OpenMAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.OpenMAMLPlusAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.PACOHAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.PEARLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.PMFAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ProtoNetsAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.PTMAPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.R2D2Algorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.RCNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.RecurrentHyperNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.RelationNetworkAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.ReptileAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SDCLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SEALAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SetFeatAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SIBAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SImPaAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SimpleShotAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SNAILAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SparseMAMLAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SteerCNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.SwinTNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.TADAMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.TaskCondHyperNetAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.TETNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.TIMAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.TNPAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.UnsupervisedMetaLearnAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.VERSAAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Algorithms.WarpGradAlgorithm<T, TInput, TOutput>",
            "global::AiDotNet.MetaLearning.Models.LinearVectorModel",
            "global::AiDotNet.MetaLearning.Modules.RelationModule<T>",
            "global::AiDotNet.ModelLoading.Pretrained.OnnxFullModelAdapter<T>",
            "global::AiDotNet.NeuralNetworks.ACGAN<T>",
            "global::AiDotNet.NeuralNetworks.Gpt4VisionNeuralNetwork<T>",
            "global::AiDotNet.NeuralNetworks.Pix2Pix<T>",
            "global::AiDotNet.NeuralNetworks.StyleGAN<T>",
            "global::AiDotNet.NeuralNetworks.SuperNet<T>",
            "global::AiDotNet.NeuralNetworks.WGAN<T>",
            "global::AiDotNet.PhysicsInformed.NeuralOperators.DeepOperatorNetwork<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.DeepRitzMethod<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.DomainDecompositionPINN<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.InverseProblemPINN<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.MultiFidelityPINN<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.MultiScalePINN<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.PhysicsInformedNeuralNetwork<T>",
            "global::AiDotNet.PhysicsInformed.PINNs.VariationalPINN<T>",
            "global::AiDotNet.ProgramSynthesis.Engines.CodeT5<T>",
            "global::AiDotNet.ProgramSynthesis.Engines.NeuralProgramSynthesizer<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.BetaPolicy<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.ContinuousPolicy<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.DeterministicPolicy<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.DiscretePolicy<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.MixedPolicy<T>",
            "global::AiDotNet.ReinforcementLearning.Policies.MultiModalPolicy<T>",
            "global::AiDotNet.Safety.Audio.AcousticToxicityDetector<T>",
            "global::AiDotNet.Safety.Audio.MaskingVoiceProtector<T>",
            "global::AiDotNet.Safety.Audio.PerturbationVoiceProtector<T>",
            "global::AiDotNet.Safety.Audio.SpectralDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Audio.TranscriptionToxicityDetector<T>",
            "global::AiDotNet.Safety.Audio.VoiceprintDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Audio.WatermarkDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Audio.WatermarkVoiceProtector<T>",
            "global::AiDotNet.Safety.Image.CLIPImageSafetyClassifier<T>",
            "global::AiDotNet.Safety.Image.ConsistencyDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Image.EnsembleImageSafetyClassifier<T>",
            "global::AiDotNet.Safety.Image.FrequencyDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Image.ProvenanceDeepfakeDetector<T>",
            "global::AiDotNet.Safety.Image.SceneGraphSafetyClassifier<T>",
            "global::AiDotNet.Safety.Image.ViTImageSafetyClassifier<T>",
            "global::AiDotNet.Safety.Multimodal.MultimodalGuardrail<T>",
            "global::AiDotNet.Safety.Multimodal.TextImageAlignmentChecker<T>",
            "global::AiDotNet.Safety.Text.ClassifierToxicityDetector<T>",
            "global::AiDotNet.Safety.Text.CompositePIIDetector<T>",
            "global::AiDotNet.Safety.Text.ContextAwarePIIDetector<T>",
            "global::AiDotNet.Safety.Text.EmbeddingCopyrightDetector<T>",
            "global::AiDotNet.Safety.Text.EmbeddingToxicityDetector<T>",
            "global::AiDotNet.Safety.Text.EnsembleJailbreakDetector<T>",
            "global::AiDotNet.Safety.Text.EnsembleToxicityDetector<T>",
            "global::AiDotNet.Safety.Text.EntailmentHallucinationDetector<T>",
            "global::AiDotNet.Safety.Text.GradientJailbreakDetector<T>",
            "global::AiDotNet.Safety.Text.KnowledgeTripletHallucinationDetector<T>",
            "global::AiDotNet.Safety.Text.NERPIIDetector<T>",
            "global::AiDotNet.Safety.Text.NgramCopyrightDetector<T>",
            "global::AiDotNet.Safety.Text.PatternJailbreakDetector<T>",
            "global::AiDotNet.Safety.Text.PerplexityMemorizationDetector<T>",
            "global::AiDotNet.Safety.Text.ReferenceBasedHallucinationDetector<T>",
            "global::AiDotNet.Safety.Text.RegexPIIDetector<T>",
            "global::AiDotNet.Safety.Text.RuleBasedToxicityDetector<T>",
            "global::AiDotNet.Safety.Text.SelfConsistencyHallucinationDetector<T>",
            "global::AiDotNet.Safety.Text.SemanticJailbreakDetector<T>",
            "global::AiDotNet.Safety.Video.FrameSamplingVideoModerator<T>",
            "global::AiDotNet.Safety.Video.MultimodalVideoModerator<T>",
            "global::AiDotNet.Safety.Video.TemporalConsistencyDetector<T>",
            "global::AiDotNet.Safety.Watermarking.AudioSealWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.AudioWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.FrequencyImageWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.ImageWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.InvisibleImageWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.LexicalWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.NeuralImageWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.SamplingWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.SpectralAudioWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.SyntacticWatermarker<T>",
            "global::AiDotNet.Safety.Watermarking.WatermarkDetector<T>",
            "global::AiDotNet.SelfSupervisedLearning.BarlowTwins<T>",
            "global::AiDotNet.SelfSupervisedLearning.BYOL<T>",
            "global::AiDotNet.SelfSupervisedLearning.CenteringMechanism<T>",
            "global::AiDotNet.SelfSupervisedLearning.DINO<T>",
            "global::AiDotNet.SelfSupervisedLearning.Evaluation.KNNEvaluator<T>",
            "global::AiDotNet.SelfSupervisedLearning.iBOT<T>",
            "global::AiDotNet.SelfSupervisedLearning.MAE<T>",
            "global::AiDotNet.SelfSupervisedLearning.MoCo<T>",
            "global::AiDotNet.SelfSupervisedLearning.MoCoV2<T>",
            "global::AiDotNet.SelfSupervisedLearning.MoCoV3<T>",
            "global::AiDotNet.SelfSupervisedLearning.SimCLR<T>",
            "global::AiDotNet.SelfSupervisedLearning.SimSiam<T>",
            "global::AiDotNet.SpeechRecognition.ConformerFamily.Branchformer<T>",
            "global::AiDotNet.SpeechRecognition.ConformerFamily.EBranchformer<T>",
            "global::AiDotNet.SpeechRecognition.LLMIntegrated.AudioPaLM<T>",
            "global::AiDotNet.TextToSpeech.CodecBased.AudioLM<T>",
            "global::AiDotNet.TextToSpeech.CodecBased.CosyVoice2<T>",
            "global::AiDotNet.TextToSpeech.CodecBased.FishSpeech<T>",
            "global::AiDotNet.TextToSpeech.CodecBased.VALLE<T>",
            "global::AiDotNet.TextToSpeech.CodecBased.VoiceCraft<T>",
            "global::AiDotNet.TextToSpeech.FlowDiffusion.MatchaTTS<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.AmazonPolly<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.AzureNeuralTTS<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.ElevenLabsTTS<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.GoogleCloudTTS<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.Murf<T>",
            "global::AiDotNet.TextToSpeech.ProprietaryAPI.NVIDIARivaTTS<T>",
            "global::AiDotNet.TextToSpeech.StyleEmotion.StyleTTS2<T>",
            "global::AiDotNet.TextToSpeech.Vocoders.WaveNet<T>",
            "global::AiDotNet.VisionLanguage.Editing.EmuEdit<T>",
            "global::AiDotNet.VisionLanguage.Editing.MGIE<T>",
            "global::AiDotNet.VisionLanguage.Editing.SmartEdit<T>",
            "global::AiDotNet.VisionLanguage.Grounding.Ferret<T>",
            "global::AiDotNet.VisionLanguage.Grounding.FerretV2<T>",
            "global::AiDotNet.VisionLanguage.Grounding.Groma<T>",
            "global::AiDotNet.VisionLanguage.Grounding.GroundedSAM2<T>",
            "global::AiDotNet.VisionLanguage.Grounding.Shikra<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.AquilaVL<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Aria<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Cambrian1<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Dragonfly<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Eagle<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Eagle25<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.LLaVA15<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.LLaVANeXT<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.LLaVAOneVision<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.LLaVAOneVision15<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Mantis<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Maya<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.MiniCPMo<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.MiniCPMV<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Molmo<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Monkey<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Moondream<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.NVLM<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.Ovis<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.VILA<T>",
            "global::AiDotNet.VisionLanguage.InstructionTuned.VILAU<T>",
            "global::AiDotNet.VisionLanguage.Medical.DragonflyMed<T>",
            "global::AiDotNet.VisionLanguage.Medical.LLaVAMed<T>",
            "global::AiDotNet.VisionLanguage.Medical.PathVLM<T>",
            "global::AiDotNet.VisionLanguage.Medical.RadFM<T>",
            "global::AiDotNet.VisionLanguage.Reasoning.LLaVACoT<T>",
            "global::AiDotNet.VisionLanguage.Reasoning.QVQ72B<T>",
            "global::AiDotNet.VisionLanguage.Reasoning.SkyworkR1V<T>",
            "global::AiDotNet.VisionLanguage.Reasoning.SkyworkR1V2<T>",
            "global::AiDotNet.VisionLanguage.RemoteSensing.GeoChat<T>",
            "global::AiDotNet.VisionLanguage.RemoteSensing.RSGPT<T>",
            "global::AiDotNet.VisionLanguage.RemoteSensing.SkyEyeGPT<T>",
        };
}