using AiDotNet.Attributes;
using AiDotNet.Autodiff;
using AiDotNet.Helpers;
using AiDotNet.Interfaces;

namespace AiDotNet.NeuralNetworks.Layers.SSM;

/// <summary>
/// Implements the Hyena layer from "Hyena Hierarchy: Towards Larger Convolutional Language Models"
/// (Poli et al., 2023, arXiv:2302.10866).
/// </summary>
/// <remarks>
/// <para>
/// Hyena replaces the standard attention mechanism with a hierarchy of long implicit convolutions
/// gated by data-dependent projections. This achieves sub-quadratic O(N log N) complexity while
/// matching or approaching Transformer quality on many sequence modeling benchmarks.
/// </para>
/// <para>
/// The architecture works as follows:
/// <code>
///   1. The input x is projected into (order + 1) linear projections: v, x_1, x_2, ..., x_N
///      where N = order (default 2). The projection v serves as the initial value signal.
///   2. Each x_i is passed through a short element-wise activation to produce a data-dependent gate.
///   3. Long convolution filters h_1, h_2, ..., h_N are generated by a small MLP (the "implicit filter")
///      that takes positional encodings as input. This means the convolution kernels are not stored
///      explicitly but are parameterized by a compact neural network.
///   4. The computation unfolds as a gated convolution hierarchy:
///      y = x_N * (h_N conv (x_{N-1} * (h_{N-1} conv ... (h_1 conv (x_1 * v)) ...)))
///      where * denotes element-wise multiplication (gating) and "conv" denotes long convolution.
///   5. An output projection maps the result back to model dimension.
/// </code>
/// </para>
/// <para>
/// The long convolutions are the key innovation. Instead of storing an explicit kernel of length L
/// (which would be expensive for long sequences), Hyena uses a small MLP that takes a positional
/// encoding t/L as input and outputs the filter value h(t). This "implicit parameterization" means
/// the filter can span the entire sequence length with very few parameters. The convolution itself
/// can be computed efficiently in O(N log N) via FFT, though this implementation uses time-domain
/// convolution for clarity and correctness.
/// </para>
/// <para>
/// <b>For Beginners:</b> Hyena is an alternative to the attention mechanism used in Transformers.
///
/// In a standard Transformer, every token "looks at" every other token via attention, which costs
/// O(N^2) time for a sequence of length N. Hyena achieves a similar effect more efficiently:
///
/// - Instead of attention, it uses <b>long convolutions</b> that slide a filter across the entire
///   sequence. Think of this like a sliding window that can "see" all positions.
/// - The convolution filters are not stored as giant arrays. Instead, a tiny neural network generates
///   the filter values on the fly from position numbers. This is called an "implicit filter."
/// - Between convolution steps, <b>data-dependent gates</b> (element-wise multiplications with
///   projections of the input) allow the model to selectively amplify or suppress information,
///   similar to how attention selectively focuses on relevant tokens.
/// - Stacking multiple rounds of "gate then convolve" (controlled by the <c>order</c> parameter)
///   gives the model enough expressivity to rival attention.
///
/// The result: Hyena can process much longer sequences than standard Transformers, because its
/// cost grows as O(N log N) instead of O(N^2).
/// </para>
/// <para>
/// <b>Reference:</b> Poli et al., "Hyena Hierarchy: Towards Larger Convolutional Language Models", 2023.
/// <see href="https://arxiv.org/abs/2302.10866"/>
/// </para>
/// </remarks>
/// <typeparam name="T">The numeric type used for calculations, typically float or double.</typeparam>
[LayerCategory(LayerCategory.StateSpaceModel)]
[LayerTask(LayerTask.SequenceModeling)]
[LayerTask(LayerTask.TemporalProcessing)]
[LayerProperty(IsTrainable = true, IsStateful = true, Cost = ComputeCost.High, TestInputShape = "4, 256", TestConstructorArgs = "4")]
public class HyenaLayer<T> : LayerBase<T>
{
    private readonly int _sequenceLength;
    private readonly int _modelDimension;
    private readonly int _order;
    private readonly int _filterDim;

    // Input projections: (order + 1) projections, each [modelDim, modelDim]
    // Index 0 = value projection (v), indices 1..order = gate projections (x_1..x_N)
    private Tensor<T>[] _inputProjectionWeights;
    private Tensor<T>[] _inputProjectionBiases;

    // Implicit filter network: one small MLP per convolution (order MLPs total)
    // Each MLP: input(1) -> hidden(filterDim) -> output(modelDim)
    // Layer 1: [1, filterDim]  (positional encoding -> hidden)
    // Layer 2: [filterDim, modelDim] (hidden -> filter value per dimension)
    private Tensor<T>[] _filterWeights1;
    private Tensor<T>[] _filterBiases1;
    private Tensor<T>[] _filterWeights2;
    private Tensor<T>[] _filterBiases2;

    // Output projection: [modelDim, modelDim]
    private Tensor<T> _outputProjectionWeights;
    private Tensor<T> _outputProjectionBias;

    // Cached values for backward pass
    private Tensor<T>? _lastInput;
    private Tensor<T>? _lastOutput;
    private Tensor<T>[]? _lastProjections;       // (order+1) projections: v, x_1, ..., x_N
    private Tensor<T>[]? _lastProjectionsRaw;     // pre-activation raw projections
    private Tensor<T>[]? _lastFilters;            // generated filter kernels [seqLen, modelDim]
    private Tensor<T>[]? _lastFilterHidden;       // hidden states from filter MLPs
    private Tensor<T>[]? _lastConvOutputs;        // results after each convolution
    private Tensor<T>[]? _lastGatedOutputs;       // results after each gating step
    private Tensor<T>? _lastPreProjection;        // result before output projection
    private int[]? _originalInputShape;

    // Gradients for input projections
    private Tensor<T>[]? _inputProjectionWeightsGradients;
    private Tensor<T>[]? _inputProjectionBiasesGradients;

    // Gradients for filter networks
    private Tensor<T>[]? _filterWeights1Gradients;
    private Tensor<T>[]? _filterBiases1Gradients;
    private Tensor<T>[]? _filterWeights2Gradients;
    private Tensor<T>[]? _filterBiases2Gradients;

    // Gradients for output projection
    private Tensor<T>? _outputProjectionWeightsGradient;
    private Tensor<T>? _outputProjectionBiasGradient;

    /// <inheritdoc />
    public override bool SupportsTraining => true;

    /// <summary>
    /// Gets the sequence length this layer was configured for.
    /// </summary>
    public int SequenceLength => _sequenceLength;

    /// <summary>
    /// Gets the model dimension.
    /// </summary>
    public int ModelDimension => _modelDimension;

    /// <summary>
    /// Gets the Hyena order (number of gated convolution stages).
    /// </summary>
    public int Order => _order;

    /// <summary>
    /// Gets the hidden dimension of the implicit filter network.
    /// </summary>
    public int FilterDim => _filterDim;

    /// <summary>
    /// Gets the total number of trainable parameters.
    /// </summary>
    public override int ParameterCount
    {
        get
        {
            int count = 0;

            // Input projections: (order + 1) x (weights + bias)
            for (int i = 0; i <= _order; i++)
            {
                count += _inputProjectionWeights[i].Length;
                count += _inputProjectionBiases[i].Length;
            }

            // Filter networks: order x (W1 + b1 + W2 + b2)
            for (int i = 0; i < _order; i++)
            {
                count += _filterWeights1[i].Length;
                count += _filterBiases1[i].Length;
                count += _filterWeights2[i].Length;
                count += _filterBiases2[i].Length;
            }

            // Output projection
            count += _outputProjectionWeights.Length;
            count += _outputProjectionBias.Length;

            return count;
        }
    }

    /// <summary>
    /// Creates a new Hyena layer.
    /// </summary>
    /// <param name="sequenceLength">
    /// Maximum sequence length. The implicit filter will generate convolution kernels of this length.
    /// </param>
    /// <param name="modelDimension">
    /// Model dimension (d_model). Default: 256.
    /// <para><b>For Beginners:</b> This is the width of the representation at each position in the sequence.
    /// Larger values let the model represent more information but use more memory.</para>
    /// </param>
    /// <param name="order">
    /// Number of gated convolution stages in the Hyena hierarchy. Default: 2.
    /// <para><b>For Beginners:</b> This controls how many rounds of "gate then convolve" are applied.
    /// Order 2 (the default from the paper) means: gate with x_1, convolve with h_1, gate with x_2,
    /// convolve with h_2. Higher orders give more expressivity but cost more computation.</para>
    /// </param>
    /// <param name="filterDim">
    /// Hidden dimension of the implicit filter MLP. Default: 64.
    /// <para><b>For Beginners:</b> The implicit filter is a small neural network that generates
    /// convolution kernels from position numbers. This parameter controls the width of that
    /// small network. Larger values allow more expressive filters.</para>
    /// </param>
    /// <param name="activationFunction">Optional activation function applied to the final output.</param>
    /// <exception cref="ArgumentException">Thrown when parameters are invalid.</exception>
    public HyenaLayer(
        int sequenceLength,
        int modelDimension = 256,
        int order = 2,
        int filterDim = 64,
        IActivationFunction<T>? activationFunction = null,
        IInitializationStrategy<T>? initializationStrategy = null)
        : base(
            [sequenceLength, modelDimension],
            [sequenceLength, modelDimension],
            activationFunction ?? new IdentityActivation<T>())
    {
        InitializationStrategy = initializationStrategy ?? InitializationStrategies<T>.Eager;

        if (sequenceLength <= 0)
            throw new ArgumentException($"Sequence length ({sequenceLength}) must be positive.", nameof(sequenceLength));
        if (modelDimension <= 0)
            throw new ArgumentException($"Model dimension ({modelDimension}) must be positive.", nameof(modelDimension));
        if (order <= 0)
            throw new ArgumentException($"Order ({order}) must be positive.", nameof(order));
        if (filterDim <= 0)
            throw new ArgumentException($"Filter dimension ({filterDim}) must be positive.", nameof(filterDim));

        _sequenceLength = sequenceLength;
        _modelDimension = modelDimension;
        _order = order;
        _filterDim = filterDim;

        // Allocate input projections: (order + 1) projections for v, x_1, ..., x_N
        _inputProjectionWeights = new Tensor<T>[order + 1];
        _inputProjectionBiases = new Tensor<T>[order + 1];
        for (int i = 0; i <= order; i++)
        {
            _inputProjectionWeights[i] = new Tensor<T>([modelDimension, modelDimension]);
            _inputProjectionBiases[i] = new Tensor<T>([modelDimension]);
        }

        // Allocate implicit filter networks: one MLP per convolution stage
        _filterWeights1 = new Tensor<T>[order];
        _filterBiases1 = new Tensor<T>[order];
        _filterWeights2 = new Tensor<T>[order];
        _filterBiases2 = new Tensor<T>[order];
        for (int i = 0; i < order; i++)
        {
            _filterWeights1[i] = new Tensor<T>([1, filterDim]);
            _filterBiases1[i] = new Tensor<T>([filterDim]);
            _filterWeights2[i] = new Tensor<T>([filterDim, modelDimension]);
            _filterBiases2[i] = new Tensor<T>([modelDimension]);
        }

        // Output projection
        _outputProjectionWeights = new Tensor<T>([modelDimension, modelDimension]);
        _outputProjectionBias = new Tensor<T>([modelDimension]);

        InitializeParameters();
    }

    private void InitializeParameters()
    {
        // Initialize input projections with Xavier/Glorot
        for (int i = 0; i <= _order; i++)
        {
            InitializeTensor2D(_inputProjectionWeights[i]);
            _inputProjectionBiases[i].Fill(NumOps.Zero);
        }

        // Initialize filter network weights
        for (int i = 0; i < _order; i++)
        {
            InitializeTensor2D(_filterWeights1[i]);
            _filterBiases1[i].Fill(NumOps.Zero);
            InitializeTensor2D(_filterWeights2[i]);
            _filterBiases2[i].Fill(NumOps.Zero);
        }

        // Initialize output projection
        InitializeTensor2D(_outputProjectionWeights);
        _outputProjectionBias.Fill(NumOps.Zero);
    }

    private void InitializeTensor2D(Tensor<T> tensor)
    {
        InitializeLayerWeights(tensor, tensor.Shape[0], tensor.Shape[1]);
    }

    /// <inheritdoc />
    public override Tensor<T> Forward(Tensor<T> input)
    {
        _originalInputShape = input.Shape.ToArray();

        int rank = input.Shape.Length;
        int seqLen = rank >= 2 ? input.Shape[rank - 2] : 1;
        int modelDim = input.Shape[rank - 1];

        int batchSize = 1;
        for (int d = 0; d < rank - 2; d++)
            batchSize *= input.Shape[d];
        if (rank < 3) batchSize = 1;

        var input3D = rank == 2
            ? input.Reshape(1, seqLen, modelDim)
            : input.Reshape(batchSize, seqLen, modelDim);

        _lastInput = input3D;

        // Step 1: Compute (order + 1) linear projections
        // Projection 0 = v (value), projections 1..order = gates x_1..x_N
        var projections = new Tensor<T>[_order + 1];
        var projectionsRaw = new Tensor<T>[_order + 1];
        var inputFlat = input3D.Reshape(batchSize * seqLen, _modelDimension);

        for (int i = 0; i <= _order; i++)
        {
            var rawProj = Engine.TensorBroadcastAdd(
                Engine.TensorMatMul(inputFlat, _inputProjectionWeights[i]),
                _inputProjectionBiases[i].Reshape(1, _modelDimension));
            projectionsRaw[i] = rawProj.Reshape(batchSize, seqLen, _modelDimension);

            // Apply element-wise activation for gates (SiLU for gates, identity for v)
            if (i == 0)
            {
                // v: no gating activation, use raw projection
                projections[i] = projectionsRaw[i];
            }
            else
            {
                // x_i gates: apply SiLU activation for data-dependent gating
                projections[i] = Engine.Swish(projectionsRaw[i]);
            }
        }

        _lastProjections = projections;
        _lastProjectionsRaw = projectionsRaw;

        // Step 2: Generate implicit convolution filters using the filter MLP
        // For each convolution stage, the MLP takes positional encodings [0/L, 1/L, ..., (L-1)/L]
        // and outputs a filter of shape [seqLen, modelDim]
        var filters = new Tensor<T>[_order];
        var filterHiddenStates = new Tensor<T>[_order];

        // Create positional encodings: [seqLen, 1] with values t/seqLen
        var posEnc = new Tensor<T>(new[] { seqLen, 1 });
        T seqLenT = NumOps.FromDouble(seqLen);
        for (int t = 0; t < seqLen; t++)
        {
            posEnc[new[] { t, 0 }] = NumOps.Divide(NumOps.FromDouble(t), seqLenT);
        }

        for (int i = 0; i < _order; i++)
        {
            // MLP layer 1: posEnc [seqLen, 1] x W1 [1, filterDim] + b1 -> [seqLen, filterDim]
            var hidden = Engine.TensorBroadcastAdd(
                Engine.TensorMatMul(posEnc, _filterWeights1[i]),
                _filterBiases1[i].Reshape(1, _filterDim));

            // Apply SiLU activation on the hidden layer
            var hiddenAct = Engine.Swish(hidden);
            filterHiddenStates[i] = hidden; // save pre-activation for backward

            // MLP layer 2: hiddenAct [seqLen, filterDim] x W2 [filterDim, modelDim] + b2 -> [seqLen, modelDim]
            var filter = Engine.TensorBroadcastAdd(
                Engine.TensorMatMul(hiddenAct, _filterWeights2[i]),
                _filterBiases2[i].Reshape(1, _modelDimension));

            filters[i] = filter;
        }

        _lastFilters = filters;
        _lastFilterHidden = filterHiddenStates;

        // Step 3: Apply the Hyena hierarchy
        // y = x_N * (h_N conv (x_{N-1} * (h_{N-1} conv ... (h_1 conv (x_1 * v)) ...)))
        // Start with: current = x_1 * v  (element-wise gate of v by first gate)
        // Then for each stage i = 1..order:
        //   current = h_i conv current   (long convolution)
        //   if i < order: current = x_{i+1} * current  (gate by next projection)

        var convOutputs = new Tensor<T>[_order];
        var gatedOutputs = new Tensor<T>[_order + 1];

        // Initial gating: current = x_1 * v
        var current = Engine.TensorMultiply(projections[1], projections[0]);
        gatedOutputs[0] = current;

        for (int i = 0; i < _order; i++)
        {
            // Apply long convolution with filter h_{i+1}
            var convResult = CausalConvolution(current, filters[i], batchSize, seqLen);
            convOutputs[i] = convResult;
            current = convResult;

            // Apply gating by x_{i+2} if there is a next gate (i.e., i < order - 1)
            if (i < _order - 1)
            {
                current = Engine.TensorMultiply(projections[i + 2], current);
            }

            gatedOutputs[i + 1] = current;
        }

        _lastConvOutputs = convOutputs;
        _lastGatedOutputs = gatedOutputs;
        _lastPreProjection = current;

        // Step 4: Output projection
        var currentFlat = current.Reshape(batchSize * seqLen, _modelDimension);
        var outputFlat = Engine.TensorBroadcastAdd(
            Engine.TensorMatMul(currentFlat, _outputProjectionWeights),
            _outputProjectionBias.Reshape(1, _modelDimension));
        var output3D = outputFlat.Reshape(batchSize, seqLen, _modelDimension);

        var result = ApplyActivation(output3D);
        _lastOutput = result;

        if (rank == 2)
            return result.Reshape(seqLen, _modelDimension);

        var outputShape = new int[rank];
        for (int i = 0; i < rank - 2; i++)
            outputShape[i] = input.Shape[i];
        outputShape[rank - 2] = seqLen;
        outputShape[rank - 1] = _modelDimension;
        return result.Reshape(outputShape);
    }

    /// <summary>
    /// Performs causal (left-padded) convolution in the time domain.
    /// </summary>
    /// <remarks>
    /// <para>
    /// For each output position t, the convolution computes:
    ///   out[t, d] = sum_{k=0}^{t} filter[k, d] * input[t - k, d]
    /// This is a causal convolution: each position only depends on current and past positions.
    /// </para>
    /// <para><b>For Beginners:</b> Convolution slides a filter across the input. "Causal" means
    /// each output position only looks at the current and earlier input positions, not future ones.
    /// This is essential for autoregressive (left-to-right) sequence modeling.</para>
    /// </remarks>
    private Tensor<T> CausalConvolution(Tensor<T> input, Tensor<T> filter, int batchSize, int seqLen)
    {
        // input: [batch, seqLen, modelDim]
        // filter: [seqLen, modelDim] (implicit filter, same for all batches)
        // output: [batch, seqLen, modelDim]
        var output = TensorAllocator.Rent<T>(new[] { batchSize, seqLen, _modelDimension });

        for (int bi = 0; bi < batchSize; bi++)
        {
            for (int t = 0; t < seqLen; t++)
            {
                for (int d = 0; d < _modelDimension; d++)
                {
                    T sum = NumOps.Zero;
                    // Causal: only sum over k from 0 to t
                    for (int k = 0; k <= t; k++)
                    {
                        T filterVal = filter[new[] { k, d }];
                        T inputVal = input[new[] { bi, t - k, d }];
                        sum = NumOps.Add(sum, NumOps.Multiply(filterVal, inputVal));
                    }
                    output[new[] { bi, t, d }] = sum;
                }
            }
        }

        return output;
    }

    /// <summary>
    /// Computes the derivative of the SiLU (Swish) activation function.
    /// </summary>
    /// <remarks>
    /// SiLU(x) = x * sigmoid(x). Its derivative is:
    /// SiLU'(x) = sigmoid(x) * (1 + x * (1 - sigmoid(x)))
    /// </remarks>
    private Tensor<T> ComputeSiLUDerivative(Tensor<T> x)
    {
        var sig = Engine.Sigmoid(x);
        var ones = new Tensor<T>(x.Shape.ToArray());
        ones.Fill(NumOps.One);
        var oneMinusSig = Engine.TensorSubtract(ones, sig);
        var xTimesOneMinusSig = Engine.TensorMultiply(x, oneMinusSig);
        var onePlusXSig = Engine.TensorAdd(ones, xTimesOneMinusSig);
        return Engine.TensorMultiply(sig, onePlusXSig);
    }

    #region Parameter Management

    /// <inheritdoc />
    public override void UpdateParameters(T learningRate)
    {
        if (_inputProjectionWeightsGradients == null || _inputProjectionBiasesGradients == null ||
            _filterWeights1Gradients == null || _filterBiases1Gradients == null ||
            _filterWeights2Gradients == null || _filterBiases2Gradients == null ||
            _outputProjectionWeightsGradient == null || _outputProjectionBiasGradient == null)
            throw new InvalidOperationException("Backward pass must be called before updating parameters.");

        T negLR = NumOps.Negate(learningRate);

        // Update input projections
        for (int i = 0; i <= _order; i++)
        {
            _inputProjectionWeights[i] = Engine.TensorAdd(
                _inputProjectionWeights[i],
                Engine.TensorMultiplyScalar(_inputProjectionWeightsGradients[i], negLR));
            _inputProjectionBiases[i] = Engine.TensorAdd(
                _inputProjectionBiases[i],
                Engine.TensorMultiplyScalar(_inputProjectionBiasesGradients[i], negLR));
        }

        // Update filter networks
        for (int i = 0; i < _order; i++)
        {
            _filterWeights1[i] = Engine.TensorAdd(
                _filterWeights1[i],
                Engine.TensorMultiplyScalar(_filterWeights1Gradients[i], negLR));
            _filterBiases1[i] = Engine.TensorAdd(
                _filterBiases1[i],
                Engine.TensorMultiplyScalar(_filterBiases1Gradients[i], negLR));
            _filterWeights2[i] = Engine.TensorAdd(
                _filterWeights2[i],
                Engine.TensorMultiplyScalar(_filterWeights2Gradients[i], negLR));
            _filterBiases2[i] = Engine.TensorAdd(
                _filterBiases2[i],
                Engine.TensorMultiplyScalar(_filterBiases2Gradients[i], negLR));
        }

        // Update output projection
        _outputProjectionWeights = Engine.TensorAdd(
            _outputProjectionWeights,
            Engine.TensorMultiplyScalar(_outputProjectionWeightsGradient, negLR));
        _outputProjectionBias = Engine.TensorAdd(
            _outputProjectionBias,
            Engine.TensorMultiplyScalar(_outputProjectionBiasGradient, negLR));
    }

    /// <inheritdoc />
    public override Vector<T> GetParameters()
    {
        var parameters = new Vector<T>(ParameterCount);
        int index = 0;
        foreach (var tensor in GetAllTensors())
            for (int i = 0; i < tensor.Length; i++)
                parameters[index++] = tensor[i];
        return parameters;
    }

    /// <inheritdoc />
    public override Vector<T> GetParameterGradients()
    {
        var result = new Vector<T>(ParameterCount);
        int index = 0;

        // Input projections — same order as GetAllTensors()
        for (int i = 0; i <= _order; i++)
        {
            var wGrad = _inputProjectionWeightsGradients?[i];
            var bGrad = _inputProjectionBiasesGradients?[i];

            if (wGrad != null)
                for (int j = 0; j < wGrad.Length; j++) result[index++] = wGrad[j];
            else
                index += _inputProjectionWeights[i].Length;

            if (bGrad != null)
                for (int j = 0; j < bGrad.Length; j++) result[index++] = bGrad[j];
            else
                index += _inputProjectionBiases[i].Length;
        }

        // Filter networks
        for (int i = 0; i < _order; i++)
        {
            var fw1Grad = _filterWeights1Gradients?[i];
            var fb1Grad = _filterBiases1Gradients?[i];
            var fw2Grad = _filterWeights2Gradients?[i];
            var fb2Grad = _filterBiases2Gradients?[i];

            if (fw1Grad != null)
                for (int j = 0; j < fw1Grad.Length; j++) result[index++] = fw1Grad[j];
            else
                index += _filterWeights1[i].Length;

            if (fb1Grad != null)
                for (int j = 0; j < fb1Grad.Length; j++) result[index++] = fb1Grad[j];
            else
                index += _filterBiases1[i].Length;

            if (fw2Grad != null)
                for (int j = 0; j < fw2Grad.Length; j++) result[index++] = fw2Grad[j];
            else
                index += _filterWeights2[i].Length;

            if (fb2Grad != null)
                for (int j = 0; j < fb2Grad.Length; j++) result[index++] = fb2Grad[j];
            else
                index += _filterBiases2[i].Length;
        }

        // Output projection
        if (_outputProjectionWeightsGradient != null)
            for (int j = 0; j < _outputProjectionWeightsGradient.Length; j++) result[index++] = _outputProjectionWeightsGradient[j];
        else
            index += _outputProjectionWeights.Length;

        if (_outputProjectionBiasGradient != null)
            for (int j = 0; j < _outputProjectionBiasGradient.Length; j++) result[index++] = _outputProjectionBiasGradient[j];

        return result;
    }

    /// <inheritdoc />
    public override void ClearGradients()
    {
        base.ClearGradients();
        _inputProjectionWeightsGradients = null;
        _inputProjectionBiasesGradients = null;
        _filterWeights1Gradients = null;
        _filterBiases1Gradients = null;
        _filterWeights2Gradients = null;
        _filterBiases2Gradients = null;
        _outputProjectionWeightsGradient = null;
        _outputProjectionBiasGradient = null;
    }

    /// <inheritdoc />
    public override void SetParameters(Vector<T> parameters)
    {
        if (parameters.Length != ParameterCount)
            throw new ArgumentException($"Expected {ParameterCount} parameters, got {parameters.Length}");
        int index = 0;
        foreach (var tensor in GetAllTensors())
            for (int i = 0; i < tensor.Length; i++)
                tensor[i] = parameters[index++];
    }

    private Tensor<T>[] GetAllTensors()
    {
        var tensors = new List<Tensor<T>>();

        // Input projections
        for (int i = 0; i <= _order; i++)
        {
            tensors.Add(_inputProjectionWeights[i]);
            tensors.Add(_inputProjectionBiases[i]);
        }

        // Filter networks
        for (int i = 0; i < _order; i++)
        {
            tensors.Add(_filterWeights1[i]);
            tensors.Add(_filterBiases1[i]);
            tensors.Add(_filterWeights2[i]);
            tensors.Add(_filterBiases2[i]);
        }

        // Output projection
        tensors.Add(_outputProjectionWeights);
        tensors.Add(_outputProjectionBias);

        return tensors.ToArray();
    }

    /// <inheritdoc />
    public override void ResetState()
    {
        _lastInput = null;
        _lastOutput = null;
        _lastProjections = null;
        _lastProjectionsRaw = null;
        _lastFilters = null;
        _lastFilterHidden = null;
        _lastConvOutputs = null;
        _lastGatedOutputs = null;
        _lastPreProjection = null;
        _originalInputShape = null;
        _inputProjectionWeightsGradients = null;
        _inputProjectionBiasesGradients = null;
        _filterWeights1Gradients = null;
        _filterBiases1Gradients = null;
        _filterWeights2Gradients = null;
        _filterBiases2Gradients = null;
        _outputProjectionWeightsGradient = null;
        _outputProjectionBiasGradient = null;
    }

    #endregion

    internal override Dictionary<string, string> GetMetadata()
    {
        var metadata = base.GetMetadata();
        metadata["SequenceLength"] = _sequenceLength.ToString();
        metadata["ModelDimension"] = _modelDimension.ToString();
        metadata["Order"] = _order.ToString();
        metadata["FilterDim"] = _filterDim.ToString();
        return metadata;
    }

    /// <summary>
    /// Gets the output projection weights for external inspection.
    /// </summary>
    public Tensor<T> GetOutputProjectionWeights() => _outputProjectionWeights;

    /// <summary>
    /// Gets the input projection weights for a given index (0 = value, 1..N = gates).
    /// </summary>
    /// <param name="index">Projection index (0 for value, 1 to order for gates).</param>
    public Tensor<T> GetInputProjectionWeights(int index)
    {
        if (index < 0 || index > _order)
            throw new ArgumentOutOfRangeException(nameof(index),
                $"Index must be between 0 and {_order}.");
        return _inputProjectionWeights[index];
    }
}
