using AiDotNet.Attributes;
using AiDotNet.DecompositionMethods.MatrixDecomposition;
using AiDotNet.Enums;
using AiDotNet.Extensions;
using AiDotNet.Helpers;
using AiDotNet.Models.Options;

namespace AiDotNet.CausalDiscovery.Functional;

/// <summary>
/// ICA-LiNGAM — Linear Non-Gaussian Acyclic Model using Independent Component Analysis.
/// </summary>
/// <remarks>
/// <para>
/// ICA-LiNGAM exploits the identifiability of the linear model X = BX + e when the noise e
/// is non-Gaussian. Using ICA (Independent Component Analysis), it recovers the mixing matrix
/// and derives the causal ordering and edge weights.
/// </para>
/// <para>
/// <b>Key insight:</b> In a linear Gaussian model, the causal direction is not identifiable
/// from observational data alone. But with non-Gaussian noise, the ICA decomposition uniquely
/// determines the causal structure — this is the LiNGAM identifiability result.
/// </para>
/// <para>
/// <b>Algorithm:</b>
/// <list type="number">
/// <item>Standardize data to zero mean, unit variance</item>
/// <item>Apply ICA (FastICA) to recover independent components S and mixing matrix A</item>
/// <item>Recover B = I - inv(A) (causal adjacency matrix)</item>
/// <item>Find a permutation that makes B lower-triangular (causal order)</item>
/// <item>Prune small coefficients</item>
/// </list>
/// </para>
/// <para>
/// <b>For Beginners:</b> If you have data generated by a linear causal model with noise
/// that isn't perfectly bell-shaped (non-Gaussian), ICA-LiNGAM can figure out the complete
/// causal structure — not just which edges exist, but which direction they go.
/// </para>
/// <para>
/// Reference: Shimizu et al. (2006), "A Linear Non-Gaussian Acyclic Model for Causal Discovery",
/// Journal of Machine Learning Research.
/// </para>
/// </remarks>
/// <typeparam name="T">The numeric type used for calculations.</typeparam>
[ModelDomain(ModelDomain.MachineLearning)]
[ModelDomain(ModelDomain.Causal)]
[ModelCategory(ModelCategory.CausalModel)]
[ModelCategory(ModelCategory.Statistical)]
[ModelTask(ModelTask.CausalInference)]
[ModelComplexity(ModelComplexity.High)]
[ModelInput(typeof(Matrix<>), typeof(Matrix<>))]
[ResearchPaper("A Linear Non-Gaussian Acyclic Model for Causal Discovery", "https://jmlr.org/papers/v7/shimizu06a.html", Year = 2006, Authors = "Shohei Shimizu, Patrik O. Hoyer, Aapo Hyvarinen, Antti Kerminen")]
public class ICALiNGAMAlgorithm<T> : FunctionalBase<T>
{
    /// <inheritdoc/>
    public override string Name => "ICA-LiNGAM";

    /// <inheritdoc/>
    public override bool SupportsNonlinear => false;

    private double _threshold = 0.1;

    /// <summary>
    /// Initializes ICA-LiNGAM with optional configuration.
    /// </summary>
    public ICALiNGAMAlgorithm(CausalDiscoveryOptions? options = null)
    {
        if (options?.EdgeThreshold.HasValue == true)
        {
            double threshold = options.EdgeThreshold.Value;
            if (double.IsNaN(threshold) || double.IsInfinity(threshold) || threshold < 0)
                throw new ArgumentException("EdgeThreshold must be a non-negative finite value.", nameof(options));
            _threshold = threshold;
        }
    }

    /// <inheritdoc/>
    protected override Matrix<T> DiscoverStructureCore(Matrix<T> data)
    {
        int n = data.Rows;
        int d = data.Columns;
        var centered = CenterData(data, n, d);
        var (whitened, whiteningMatrix) = WhitenData(centered, n, d);

        // FastICA estimates an orthogonal unmixing matrix in whitened coordinates.
        // Transform it back to the centered observation coordinates: W = Q * V.
        var whitenedUnmixing = FastICA(whitened, n, d);
        var unmixing = whitenedUnmixing.Multiply(whiteningMatrix);

        // ICA determines components only up to row permutation. LiNGAM step 2 solves
        // the linear assignment min sum_i 1 / |W[phi(i), i]|.
        int[] rowForColumn = FindRowPermutation(unmixing, d);

        // LiNGAM steps 3-4: normalize each assigned row to make the diagonal one,
        // then recover the structural coefficient matrix B = I - W'. B[target, source]
        // is converted to the repository's adjacency convention [source, target] below.
        var B = new Matrix<T>(d, d);
        for (int i = 0; i < d; i++)
        {
            T diagonal = unmixing[rowForColumn[i], i];
            if (Math.Abs(NumOps.ToDouble(diagonal)) < 1e-12)
                return new Matrix<T>(d, d);

            for (int j = 0; j < d; j++)
            {
                T normalized = NumOps.Divide(unmixing[rowForColumn[i], j], diagonal);
                B[i, j] = NumOps.Subtract(
                    i == j ? NumOps.One : NumOps.Zero,
                    normalized);
            }
        }

        // LiNGAM step 5 / Algorithms B-C: prune the smallest estimates until B can
        // be simultaneously row/column-permuted to strict lower triangular form.
        var order = FindCausalOrder(B, d);

        // Keep only coefficients allowed by the recovered order. This is the paper's
        // DAG projection, not an arbitrary tie-break: later variables may depend on
        // earlier variables, never the reverse.
        var result = new Matrix<T>(d, d);
        for (int targetPosition = 1; targetPosition < d; targetPosition++)
        {
            int target = order[targetPosition];
            for (int sourcePosition = 0; sourcePosition < targetPosition; sourcePosition++)
            {
                int source = order[sourcePosition];
                T val = B[target, source];
                double valD = NumOps.ToDouble(val);
                if (Math.Abs(valD) >= _threshold)
                    result[source, target] = val;
            }
        }

        return result;
    }

    private Matrix<T> CenterData(Matrix<T> data, int n, int d)
    {
        var centered = new Matrix<T>(n, d);
        T nT = NumOps.FromDouble(n);
        for (int j = 0; j < d; j++)
        {
            T mean = NumOps.Zero;
            for (int i = 0; i < n; i++) mean = NumOps.Add(mean, data[i, j]);
            mean = NumOps.Divide(mean, nT);
            for (int i = 0; i < n; i++) centered[i, j] = NumOps.Subtract(data[i, j], mean);
        }
        return centered;
    }

    private (Matrix<T> Whitened, Matrix<T> WhiteningMatrix) WhitenData(Matrix<T> centered, int n, int d)
    {
        var covariance = new Matrix<T>(d, d);
        T invN = NumOps.FromDouble(1.0 / n);
        for (int row = 0; row < d; row++)
        {
            for (int col = 0; col < d; col++)
            {
                T sum = NumOps.Zero;
                for (int sample = 0; sample < n; sample++)
                    sum = NumOps.Add(sum, NumOps.Multiply(centered[sample, row], centered[sample, col]));
                covariance[row, col] = NumOps.Multiply(sum, invN);
            }
        }

        var eigen = new EigenDecomposition<T>(covariance, EigenAlgorithmType.Jacobi);
        var whitening = new Matrix<T>(d, d);
        for (int component = 0; component < d; component++)
        {
            double eigenvalue = NumOps.ToDouble(eigen.EigenValues[component]);
            double inverseRoot = 1.0 / Math.Sqrt(Math.Max(eigenvalue, 1e-12));
            T scale = NumOps.FromDouble(inverseRoot);
            for (int feature = 0; feature < d; feature++)
                whitening[component, feature] = NumOps.Multiply(eigen.EigenVectors[feature, component], scale);
        }

        var whitened = new Matrix<T>(n, d);
        for (int sample = 0; sample < n; sample++)
        {
            for (int component = 0; component < d; component++)
            {
                T sum = NumOps.Zero;
                for (int feature = 0; feature < d; feature++)
                    sum = NumOps.Add(sum, NumOps.Multiply(centered[sample, feature], whitening[component, feature]));
                whitened[sample, component] = sum;
            }
        }

        return (whitened, whitening);
    }

    private Matrix<T> FastICA(Matrix<T> data, int n, int d)
    {
        const int DefaultSeed = 42;
        var rng = Tensors.Helpers.RandomHelper.CreateSeededRandom(DefaultSeed);
        var W = new Matrix<T>(d, d);

        // Initialize W as identity + small random perturbation
        for (int i = 0; i < d; i++)
        {
            W[i, i] = NumOps.One;
            for (int j = 0; j < d; j++)
                W[i, j] = NumOps.Add(W[i, j], NumOps.FromDouble(0.01 * (rng.NextDouble() - 0.5)));
        }

        // Deflation-based FastICA
        for (int p = 0; p < d; p++)
        {
            var w = new Vector<T>(d);
            for (int j = 0; j < d; j++) w[j] = NumOps.FromDouble(rng.NextDouble() - 0.5);
            VectorHelper.NormalizeInPlace(w);

            for (int iter = 0; iter < 200; iter++)
            {
                var wNew = new Vector<T>(d);

                // E{X * g(w^T X)} - E{g'(w^T X)} * w, using g(u) = tanh(u)
                T meanGPrime = NumOps.Zero;
                T nT = NumOps.FromDouble(n);
                for (int i = 0; i < n; i++)
                {
                    T u = NumOps.Zero;
                    for (int j = 0; j < d; j++)
                        u = NumOps.Add(u, NumOps.Multiply(w[j], data[i, j]));

                    double uD = NumOps.ToDouble(u);
                    T g = NumOps.FromDouble(Math.Tanh(uD));
                    T gPrime = NumOps.Subtract(NumOps.One, NumOps.Multiply(g, g));
                    meanGPrime = NumOps.Add(meanGPrime, gPrime);

                    for (int j = 0; j < d; j++)
                        wNew[j] = NumOps.Add(wNew[j], NumOps.Multiply(data[i, j], g));
                }

                meanGPrime = NumOps.Divide(meanGPrime, nT);
                for (int j = 0; j < d; j++)
                    wNew[j] = NumOps.Subtract(
                        NumOps.Divide(wNew[j], nT),
                        NumOps.Multiply(meanGPrime, w[j]));

                // Orthogonalize against previous components
                for (int k = 0; k < p; k++)
                {
                    T dot = NumOps.Zero;
                    for (int j = 0; j < d; j++)
                        dot = NumOps.Add(dot, NumOps.Multiply(wNew[j], W[k, j]));
                    for (int j = 0; j < d; j++)
                        wNew[j] = NumOps.Subtract(wNew[j], NumOps.Multiply(dot, W[k, j]));
                }

                VectorHelper.NormalizeInPlace(wNew);

                // Check convergence
                double diff = 0;
                for (int j = 0; j < d; j++)
                    diff += Math.Abs(Math.Abs(NumOps.ToDouble(wNew[j])) - Math.Abs(NumOps.ToDouble(w[j])));
                w = wNew;
                if (diff < 1e-6) break;
            }

            for (int j = 0; j < d; j++) W[p, j] = w[j];
        }

        return W;
    }

    private int[] FindRowPermutation(Matrix<T> unmixing, int d)
    {
        // Hungarian algorithm for the paper's O(d^3) linear-assignment formulation.
        // Columns are observed variables; each receives exactly one ICA component row.
        var u = new double[d + 1];
        var v = new double[d + 1];
        var p = new int[d + 1];
        var way = new int[d + 1];

        for (int row = 1; row <= d; row++)
        {
            p[0] = row;
            int column0 = 0;
            var minValue = Enumerable.Repeat(double.PositiveInfinity, d + 1).ToArray();
            var used = new bool[d + 1];

            do
            {
                used[column0] = true;
                int row0 = p[column0];
                double delta = double.PositiveInfinity;
                int column1 = 0;
                for (int column = 1; column <= d; column++)
                {
                    if (used[column]) continue;
                    double magnitude = Math.Abs(NumOps.ToDouble(unmixing[row0 - 1, column - 1]));
                    double cost = 1.0 / Math.Max(magnitude, 1e-12);
                    double current = cost - u[row0] - v[column];
                    if (current < minValue[column])
                    {
                        minValue[column] = current;
                        way[column] = column0;
                    }
                    if (minValue[column] < delta)
                    {
                        delta = minValue[column];
                        column1 = column;
                    }
                }

                for (int column = 0; column <= d; column++)
                {
                    if (used[column])
                    {
                        u[p[column]] += delta;
                        v[column] -= delta;
                    }
                    else
                    {
                        minValue[column] -= delta;
                    }
                }
                column0 = column1;
            }
            while (p[column0] != 0);

            do
            {
                int column1 = way[column0];
                p[column0] = p[column1];
                column0 = column1;
            }
            while (column0 != 0);
        }

        var rowForColumn = new int[d];
        for (int column = 1; column <= d; column++) rowForColumn[column - 1] = p[column] - 1;
        return rowForColumn;
    }

    private int[] FindCausalOrder(Matrix<T> B, int d)
    {
        var pruned = new double[d, d];
        var entries = new List<(double Magnitude, int Row, int Column)>(d * d);
        for (int i = 0; i < d; i++)
        {
            for (int j = 0; j < d; j++)
            {
                double value = NumOps.ToDouble(B[i, j]);
                pruned[i, j] = value;
                entries.Add((Math.Abs(value), i, j));
            }
        }

        entries.Sort((left, right) => left.Magnitude.CompareTo(right.Magnitude));
        int initiallyPruned = Math.Min(entries.Count, d * (d + 1) / 2);
        int next = 0;
        for (; next < initiallyPruned; next++)
            pruned[entries[next].Row, entries[next].Column] = 0.0;

        while (true)
        {
            int[]? order = TryFindCausalOrder(pruned, d);
            if (order is not null) return order;
            if (next >= entries.Count) return Enumerable.Range(0, d).ToArray();
            pruned[entries[next].Row, entries[next].Column] = 0.0;
            next++;
        }
    }

    private static int[]? TryFindCausalOrder(double[,] B, int d)
    {
        var remaining = new bool[d];
        for (int i = 0; i < remaining.Length; i++)
        {
            remaining[i] = true;
        }
        var order = new int[d];

        for (int position = 0; position < d; position++)
        {
            int source = -1;
            for (int row = 0; row < d && source < 0; row++)
            {
                if (!remaining[row]) continue;
                bool hasIncomingEdge = false;
                for (int column = 0; column < d; column++)
                {
                    if (remaining[column] && Math.Abs(B[row, column]) > 1e-12)
                    {
                        hasIncomingEdge = true;
                        break;
                    }
                }
                if (!hasIncomingEdge) source = row;
            }

            if (source < 0) return null;
            order[position] = source;
            remaining[source] = false;
        }

        return order;
    }
}
