[project]
id = "yfkqwpgjahoamlgckjib"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:4321"
additional_redirect_urls = ["https://www.aidotnet.dev", "https://test.aidotnet.dev"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
enable_confirmations = true
