param(
    [string]$ClBlastRoot = "C:\Users\cheat\source\repos\worktrees\gpu-496\.clblast",
    [string]$OutputRoot = "C:\Users\cheat\source\repos\worktrees\gpu-496\src\AiDotNet.Tensors\Engines\DirectGpu\OpenCL"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Normalize-Type([string]$token) {
    switch ($token) {
        "GPU" { return "GPU" }
        "CPU" { return "CPU" }
        "Accelerator" { return "accelerator" }
        "All" { return "default" }
        default { return $token }
    }
}

function Parse-ClBlastDb([string]$path) {
    $vendors = @()
    $currentVendor = $null
    $currentArch = $null

    foreach ($rawLine in Get-Content -Path $path) {
        $line = $rawLine.Trim()
        if ($line -match 'kDeviceType([A-Za-z]+)\s*,\s*"([^"]+)"') {
            $typeToken = $matches[1]
            $vendorName = $matches[2]
            $currentVendor = [pscustomobject]@{
                Type = (Normalize-Type $typeToken)
                Vendor = $vendorName
                Architectures = @()
            }
            $vendors += $currentVendor
            $currentArch = $null
            continue
        }

        if ($line -match '^\{\s*"([^"]+)"\s*,\s*\{') {
            if ($currentVendor -eq $null) { continue }
            $archName = $matches[1]
            $currentArch = [pscustomobject]@{
                Name = $archName
                Devices = @()
            }
            $currentVendor.Architectures += $currentArch
            continue
        }

        if ($line -match 'Name\{\s*"([^"]*)"\s*\}\s*,\s*Params\{\s*([^}]*)\}') {
            if ($currentArch -eq $null) { continue }
            $deviceName = $matches[1].TrimEnd()
            $paramsText = $matches[2]
            $params = @()
            foreach ($part in $paramsText.Split(',')) {
                $trimmed = $part.Trim()
                if ($trimmed.Length -eq 0) { continue }
                $params += [int]$trimmed
            }
            $currentArch.Devices += [pscustomobject]@{
                Name = $deviceName
                Params = $params
            }
            continue
        }

        if ($line -match 'kDeviceNameDefault\s*,\s*Params\{\s*([^}]*)\}') {
            if ($currentArch -eq $null) { continue }
            $paramsText = $matches[1]
            $params = @()
            foreach ($part in $paramsText.Split(',')) {
                $trimmed = $part.Trim()
                if ($trimmed.Length -eq 0) { continue }
                $params += [int]$trimmed
            }
            $currentArch.Devices += [pscustomobject]@{
                Name = "default"
                Params = $params
            }
            continue
        }
    }

    return $vendors
}

function Escape-CSharpString([string]$value) {
    return $value.Replace("\", "\\").Replace('"', '\"')
}

function Write-ClBlastDb([string]$className, [object[]]$vendors, [string]$outputPath) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// <auto-generated>")
    [void]$sb.AppendLine("// This file is generated from CLBlast database headers.")
    [void]$sb.AppendLine("// </auto-generated>")
    [void]$sb.AppendLine("namespace AiDotNet.Tensors.Engines.DirectGpu.OpenCL;")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("internal static class $className")
    [void]$sb.AppendLine("{")
    [void]$sb.AppendLine("    internal static readonly ClBlastVendorEntry[] Vendors = new[]")
    [void]$sb.AppendLine("    {")

    foreach ($vendor in $vendors) {
        $vendorName = Escape-CSharpString $vendor.Vendor
        $vendorType = Escape-CSharpString $vendor.Type
        [void]$sb.AppendLine("        new ClBlastVendorEntry(`"$vendorType`", `"$vendorName`", new[]")
        [void]$sb.AppendLine("        {")

        foreach ($arch in $vendor.Architectures) {
            $archName = Escape-CSharpString $arch.Name
            [void]$sb.AppendLine("            new ClBlastArchitectureEntry(`"$archName`", new[]")
            [void]$sb.AppendLine("            {")
            foreach ($device in $arch.Devices) {
                $deviceName = Escape-CSharpString $device.Name
                $paramValues = $device.Params -join ", "
                [void]$sb.AppendLine("                new ClBlastDeviceEntry(`"$deviceName`", new short[] { $paramValues }),")
            }
            [void]$sb.AppendLine("            }),")
        }

        [void]$sb.AppendLine("        }),")
    }

    [void]$sb.AppendLine("    };")
    [void]$sb.AppendLine("}")
    Set-Content -Path $outputPath -Value $sb.ToString() -Encoding ASCII
}

$dbs = @(
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/xgemm/xgemm_32.hpp"; Class = "ClBlastXgemmDatabaseData"; Output = "ClBlastXgemmDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/xgemm_direct/xgemm_direct_32.hpp"; Class = "ClBlastXgemmDirectDatabaseData"; Output = "ClBlastXgemmDirectDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/copy/copy_32.hpp"; Class = "ClBlastCopyDatabaseData"; Output = "ClBlastCopyDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/transpose/transpose_32.hpp"; Class = "ClBlastTransposeDatabaseData"; Output = "ClBlastTransposeDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/pad/pad_32.hpp"; Class = "ClBlastPadDatabaseData"; Output = "ClBlastPadDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/padtranspose/padtranspose_32.hpp"; Class = "ClBlastPadTransposeDatabaseData"; Output = "ClBlastPadTransposeDatabase.Generated.cs" },
    @{ Path = Join-Path $ClBlastRoot "src/database/kernels/gemm_routine/gemm_routine_32.hpp"; Class = "ClBlastGemmRoutineDatabaseData"; Output = "ClBlastGemmRoutineDatabase.Generated.cs" }
)

foreach ($db in $dbs) {
    $parsed = Parse-ClBlastDb $db.Path
    $outputPath = Join-Path $OutputRoot $db.Output
    Write-ClBlastDb $db.Class $parsed $outputPath
    Write-Host "Generated $($db.Output)"
}
